---
title: 'Cables sobre Propiedad Intelectual en WikiLeaks II'
author: scann
created: !!timestamp 2010-12-07 15:56:23
tags: 
    - Wikileaks
    - Libertad de expresión
    - Acceso a la información

comments: 2
nid: 280
order: 0
type: story
status: 1
format: 6
---

{% mark excerpt -%}
Tradujimos algunos más de los cables que están disponibles en el diario “El País”. Llaman la atención algunas partes de los cables, **donde se repite lo mismo que estaba en el cable anterior**, a pesar de que se supone que son dos cables diferentes sobre la situación general en España. Interesante, por cierto, las funciones que asume el **Ministerio de Cultura en defensa de la industria**. Si bien no dicen nada que no pueda ser rastreado a través de negociaciones diplomáticas tradicionales —como la <span class="caps">OMPI</span>, la <span class="caps">OMC</span>, <span class="caps">ADPIC</span>—, es interesante porque en estos cables se pone en evidencia que la ‘defensa de la *cultura*‘, tan ampliamente esgrimida y difundida por ciertos sectores, en realidad es la **defensa de las industrias**, las cuales dudosamente sean importantes para la cultura. Del mismo modo también es interesante evaluar cómo los cables hablan sólo del gobierno y de las industrias, **sin importar la sociedad civil a la cual se le aplicarán estas medidas**. Si bien no sirven para revelar nada que no se sepa, es útil leerlos para entender la **cuota de racismo, xenofobia y ‘miedo a los pobres’ involucradas en las tratativas ‘en defensa de la cultura’**.


* * * * *

**<span class="caps">CABLE</span>: [04MADRID736](http://www.elpais.com/articulo/espana/Cable/medidas/luchar/pirateria/elpepuesp/20101203elpepunac_42/Tes)**

### <span class="caps">ESPECIAL</span> 301: <span class="caps">PROGRESOS</span>, NO PERFECCIÓN

1. **<span class="caps">SUMARIO</span>**: A pesar de la fuerte voluntad política de los oficiales de gobierno y la intensificación de los esfuerzos de aplicación [ *de la ley* ] por parte de la policía, la piratería sigue siendo un problema significativo en España, ya que los piratas adaptan sus formas de hacer negocios para evitar a la policía, para sacar provecho de las lagunas legales y para utilizar mejor la Internet. **Mientras que las ventas ilegales de software han llegado a una meseta y ha habido un mínimo movimiento positivo en el porcentaje de ventas de CD ilegales, las ventas de <span class="caps">DVD</span> piratas se han incrementado ligeramente**. Los esfuerzos de aplicación son impresionantes, con más de cinco millones de grabaciones de música y sonido incautados durante las requisas. La policía tuvo éxito en frustar a los piratas durante la primera temporada de shopping. También hubo progreso en las cortes: Nike ganó control sobre su marca luego de una batalla legal de 14 años. El <span class="caps">GOE</span> (Gobierno de España) revisó su Código Penal para incrementar las penas para los delicuentes contra la propiedad intelectual, y continúa sus esfuerzos para **entrenar a los jueces** y proveer a los consumidores educación en temas de propiedad intelectual. España parece haber enfrentado a su problema de la piratería, y está comprometido a aplicar el entrenamiento y los recursos de aplicación para **ajustar la cuerda**. A la luz de estos esfuerzos y nuestra sensación del compromiso por parte del <span class="caps">GOE</span> de continuar la lucha, recomendamos **no incluir a España en la Lista de Vigilancia 301 este año**. Fin del sumario.

{%- endmark %}

h4. Clima general sobre propiedad intelectual

2. **MÚSICA, <span class="caps">VIDEOJUEGOS</span> Y PELÍCULAS**: La industria y contactos en la policía en España nos han dicho que, a lo largo de todo el año pasado, sus acciones de aplicación [ *de la ley* ] han alcanzado algún éxito en detener piratas y en reducir la venta callejera de CDs and <span class="caps">DVD</span>s. Aún así, el problema continúa siendo significativo -la piratería de discos está estimada en un rango entre 20% y 30%. La piratería de <span class="caps">DVD</span>s está estimada en un porcentaje mucho más bajo. Además, los piratas están adaptando sus métodos y ventas para frustrar al gobierno y a la industria en sus esfuerzo de aplicación. Las ventas de CDs piratas continúa siendo manejada mayormente por **inmigrantes ilegales**, que exhiben sus mercancías de CD piratas sobre mantas (“mantas”, los vendedores son por ellos llamados “manteros” en español), en las veredas de los distritos comerciales y en las estaciones de subte. Debido a que la policía ha tomado medidas enérgicas contra los manteros, algunos aspirantes a manteros están ahora intercambiando mantas para mochilas para poder vender CDs pirateados. [ *la original dice: Because police have cracked down on manteros, a few would-be manteros are now trading in blankets for backpacks to peddle pirate CDs* ]. Algunos manteros y vendedores de mochila también llevan <span class="caps">DVD</span>s. Unos pocos todavía venden videojuegos. Los piratas más sofisticados se han movido hacia la Internet. Las redes p2p en Internet también están en alza. Los representantes de la industria en Madrid nos han dicho que las ventas callejeras ahora les preocupan mucho menos que el aumento de las ventas piratas en Internet y las descargas ilegales.

3. **<span class="caps">SOFTWARE</span>**: Las ventas de software ilegal en España parecen haber bajado alrededor del 49%. Mientras esto es definitviamente una mejora por sobre las cifras del 74% en 1995, aún hay mucho trabajo por hacer. La Alianza de Software Comercial (<span class="caps">BSA</span>, por sus siglas en inglés, Business Software Alliance) trabaja con el <span class="caps">GOE</span> para incrementar la conciencia del problema en los negocios minoristas (los principales usuarios de software ilegal). Además, la policía ha tomado acciones para tratar de combatir la venta minorista de software ilegal.

4. **<span class="caps">TEMAS</span> <span class="caps">MARCARIOS</span>**: En febrero de 2004, luego de 14 años de batallas en la corte, Nike ganó una victoria mayor en la Corte Constitucional Española, que una vez más le permite a la compañía usar su marca (tanto el nombre como la insignia) en la ropa vendida en España. En respuesta a la apelación de Nike sobre una reglamentación negativa de la Corte Suprema de 1999, la Corte Constitucional Española se puso del lado de Nike, anulando la otra decisión de la corte. Se devolviló la decisión a la Corte Suprema, pidiéndole que revisara su decisión, basándose en los hallazagos de justicia de la Corte Constitucional. Nike está esperando que la nueva reglamentación de la Corte Suprema, que se espera se expida en los próximos 12 meses, será justa y objetiva.

5. **<span class="caps">PATENTES</span> DE FÁRMACOS**: El problema de las patentes de farmaceúticos de España es un legado de sus viejos procesos de la ley de patentes, que estuvo en efecto hasta Octubre de 1992. A partir de ese momento, todas las patentes farmaceúticas concedidas fueron patentes de productos. Las compañías farmaceúticas se quejaron de que los productores no-innovadores están habilitados para obtener fácilmente permisos para producir “copias legales” de sus procesos de patentado de drogas si hacen cambios menores en el proceso de producción Como otros países que tienen una historia reciente de las patentes de procedimiento [ *process patents* ], este es un problema que sólo el tiempo resolverá. Por los próximos ocho años, el legado del viejo sistema de patentes continuará fastidiando a las compañías farmaceúticas, pero hasta que todas las patentes de procedimientos no expiren, no anticipamos un cambio significativo en la situación.

6. **<span class="caps">ESFUERZO</span> DE APLICACIÓN DE LA POLICÍA**: La concentración de la policía contra delitos de propiedad intelectual, más notablemente sobre los CDs pirateados, se ha incrementado en el último año. Combinando el total de requisas para la policía nacional, la Guardia Civil y la policía municipal contra los vendedores de música, videojuegos y películas piratas excedió las 10.000 requisas en 2003. Más de cinco millones de películas y grabaciones de sonido fueron incautadas. La policía está frustrada porque las lagunas legislativas, la condición de **inmigrantes ilegales** de muchos de los apresados y las decisiones judiciales lentas y desiguales, minan muchos de sus esfuerzos. Nuestros contactos policiales creen que su efectividad será mayor cuando el Código Penal revisado entre en efecto más tarde este año (ver párrafo 8). **Además de allanar las instalaciones de producción, la policía también está avanzando en conseguir sacar a los “manteros” de la calle**. Para el año 2003, las intervenciones de la policía en el principal punto focal de piratería, Madrid, superó el doble del número atestiguado en 2002. La fuerza municipal de Madrid agregó oficiales extra al final del año específicamente para detener manteros durante el pico de vacaciones y la temporada de shopping de Navidad. En Barcelona, los frecuentes allanamientos en un local reconocido como centro para software pirata, ha reducido a la mitad la venta de programas pirateados. La policía nacional y la Guardia Civil están especialmente equipados y han aumentado su trabajo para combatir la piratería on line.

7. **<span class="caps">ESFUERZOS</span> <span class="caps">EDUCATIVOS</span>**: El año pasado, la Comisión Interministerial contra la Piratería y el Consejo Superior Judicial (un cuerpo administrativo español que supervisa las cortes), **firmaron un acuerdo para entrenar a los jueces en asuntos de propiedad intelectual**. Los dos cuerpos colaborarán en dos cursos de entrenamiento, en abril y octubre, para **entrenar de 40 a 45 jueces en cada ocasión**. Más importante aún, los contenidos de cada curso serán publicados y distribuidos a los jueces españoles por toda España. **La Oficina de Derecho de Autor en el Ministerio de Cultura también está trabajando en una campaña educativa para niños entre 12 y 18 años, para explicarles el proceso de producción y mano de obra que involucra hacer productos protegidos por derecho de autor.** El Congreso de Diputados (la cámara más baja del parlamento español) estableció un sub-comité parlamentario para poponer acciones que deberán ser tomadas para proteger la propiedad intelectual. Al finalizar el año 2003, el sub-comité publicó una serie de recomendaciones dirigidas a la burocracia gubernamental española, las agencias de publicación y la sociedad española en su conjunto, para enviar señales claras sobre la importancia de la protección de la propiedad intelectual.

8. **LA <span class="caps">REFORMA</span> <span class="caps">DEL</span> CÓDIGO <span class="caps">PENAL</span>**: El 25 de noviembre de 2003, el <span class="caps">GOE</span> modificó su Código Penal para reforzar la protección de la propiedad intelectual e industrial. El Código Penal Español revisado aumenta los castigos por los crímenes contra la propiedad intelectual, especialmente para los reincidentes. Entrará en vigencia a partir del 1 de Octubre de 2004.

### Áreas en curso de revisión

9. **<span class="caps">REGULACIONES</span> <span class="caps">SOBRE</span> PIRATERÍA <span class="caps">CON</span> <span class="caps">MEDIOS</span> ÓPTICOS**: El artículo 25 de la legislación española sobre propiedad intelectual establece un **impuesto** [ *tax: en inglés “tax” es en efecto “impuesto”, pero lo cierto es que el canon no cumple algunos de los requisitos necesarios para poder ser considerado un impuesto, por ejemplo, no es el Estado quien lo recauda, sino una entidad privada, por lo que en realidad estaríamos hablando de un canon* ] en la manufactura de equipamientos ópticos; se les solicita a los operadores aplicar para conseguir licencias. No hay ninguna legislación que requiera que los <span class="caps">SID</span> (códigos de identificación de fuentes) sean usados en CDs manufacturados localmente. A pesar de esto, **12 de 13 productores de discos compactos han firmado acuerdos de <span class="caps">SID</span> con Phillips e <span class="caps">IFPI</span>.**

10. **<span class="caps">USO</span>/CONTRATACIÓN DE <span class="caps">SOFTWARE</span> <span class="caps">PARA</span> EL <span class="caps">GOBIERNO</span>**: Como ha sido reportado previamente, en el año 2000 el <span class="caps">GOE</span> publicó directrices tituladas “La propiedad intelectual de los programas de software”. Estas directrices son para los ministerios de gobierno y delimitan medidas, recomendaciones y buenas prácticas para adquirir y utilizar software. Las directrices han sido explicadas en workshops y están ampliamente disponibles para los oficiales del gobierno español, incluso en Internet.

11. **<span class="caps">CUMPLIMIENTO</span> DE <span class="caps">ADPIC</span>**: El <span class="caps">GOE</span> se cuenta en completo cumplimiento con <span class="caps">ADPIC</span> (<span class="caps">TRIP</span>: Trade Related Aspects of Intellectual Property, Acuerdos sobre los Aspectos de Propiedad Intelectual Relacionados con el Comercio) desde 1997.

12. **APLICACIÓN**: Ver párrafo 6 arriba.

13. **<span class="caps">COMENTARIO</span>**: En nuestro cable 301 del año pasado reportamos que el gobierno español finalmente había encarado la magnitud de su problema de piratería y estaba haciendo esfuerzos de buena fe en combatirlo. Desde ese entonces, los oficiales del <span class="caps">GOE</span> en varios ministerios han continuado su trabajo en el tema y las distintas fuerzas nacionales de policía han sido excepcionales en la cantidad y el alcance de sus esfuerzos para hacer retroceder la piratería de propiedad intelectual en España. La aprobación de la revisión del Código Penal es también un buen presagio para los progresos continuados en la lucha contra los piratas. A pesar de estos y otros esfuerzos mencionados arriba, el problema de la piratería en España continúa siendo significativo. **Nuestro juicio es que las autoridades españolas son conscientes del problema y tienen la voluntad política de combatirlo. Pero tomará tiempo. Creemos que España debe permanecer fuera de la Lista Especial 301**. La inclusión de España en la lista no acelerá sus progresos y quizás sólo sirva para amortiguar, antes que fomentar, el entusiasmo en tomar acciones cuando el nuevo gobierno asuma sus funciones dentro de unos pocos meses. Al presente, nuestros contactos sobre propiedad intelectual dentro del <span class="caps">GOE</span> son receptivos y están deseosos de tomar nuestras sugerencias y escuchar nuestras preocupaciones. Continuaremos trabajando para proveer asistencia e información cuando nos sea posible —y colocar la lucha contra los piratas de la propiedad intelectual en primer lugar en nuestra agenda con los oficiales responsables en el próximo gobierno español.

<span class="caps">ARGYROS</span>


* * * * *

**<span class="caps">CABLE</span>: [05MADRID696](http://www.elpais.com/articulo/espana/Cable/acciones/legales/Gobierno/pirateria/elpepicul/20101203elpepunac_43/Tes)**

### <span class="caps">SPECIAL</span> 301 <span class="caps">RECOMMENDATION</span>

**<span class="caps">SUMARIO</span>**. La piratería en España continúa siendo un gran problema. El nuevo gobierno está formulando, en concertación con las partes interesadas, un plan integrado contra la piratería (ref. B). La industria es escéptica [ *respecto del plan* ] pero está trabajando activamente con el gobierno para **arreglar algunas lagunas legislativas**, y para **alentar una aplicación [ *de la ley* ] más efectiva**. **El <span class="caps">GOE</span> (Gobierno de España) está deseoso de trabajar con <span class="caps">USG</span> (Gobierno de <span class="caps">EEUUU</span>) en una mesa redonda sobre los derechos de propiedad intelectual**. Las agencias de aplicación de la ley española están activas en combatir la piratería de los derechos de propiedad intelectual, pero a la fecha, las acciones de aplicación de la ley no han tenido un impacto discernible sobre los niveles de piratería de la propiedad intelectual. Los representantes de las asociaciones de industrias local expresan una gran frustración sobre los niveles de piratería, y **algunos defienden [ *advocate* ] la inclusión de España en la Lista 301**. Nuestra sensación general es que el gobierno de Zapatero está compromentido en luchar contra la piratería. Dada la formación del gobierno en un plan anti-piratería integrado, el trabajo con las industrias en los asuntos legislativos, la voluntad de trabajar con el <span class="caps">USG</span> en una mesa redonda sobre derechos de propiedad intelectual y la novedad del gobierno (el gobierno de Zapatero asumió después de la última determinación del Reporte Especial 301), nuestra recomendación es que España se mantenga fuera de la Lista de Vigilancia 301 este año. Fin del sumario.

#### REUNIÓN DE <span class="caps">CHARGE</span> <span class="caps">CON</span> LA <span class="caps">VICE</span> <span class="caps">PRESIDENTA</span> <span class="caps">TERESA</span> <span class="caps">FERNANDEZ</span> DE LA <span class="caps">VEGA</span>

2. Charge enfatizó la importancia que los <span class="caps">EEUU</span> le asigna a la aplicación efectiva de los derechos de propiedad intelectual, en una reunión el 22/02/2005 (septel) con la vicepresidenta [Fernandez de la Vega](http://www.elpais.com/articulo/cultura/Congreso/aprueba/nueva/Ley/Propiedad/Intelectual/incluye/canon/copia/privada/elpporcul/20060622elpepucul_2/Tes) quien es, en efecto, la viceprimer ministro de España. De la Vega claramente entendió nuestro mensaje y estaba familiarizada con el tema. **Ella dijo que había recibido a una federación de industrias locales el día anterior para hablar sobre temas de derechos de propiedad intelectual**, y notó que era una difícil tarea sobre la cual trabajar porque había muy poca conciencia pública de que **el robo** de los derechos de propiedad intelectual estaba mal, por no hablar de que **es un crimen**.

#### <span class="caps">CLIMA</span> <span class="caps">GENERAL</span> <span class="caps">RESPECTO</span> DE LA <span class="caps">PROPIEDAD</span> <span class="caps">INTELECTUAL</span>

3. **MÚSICA**: La Alianza Internacional de Propiedad Intelectual (<span class="caps">IIPA</span>) estima que las pérdidas por piratería son de alrededor de los 90 millones de doláres en 2004. La Asociación Española de Productores de Música (<span class="caps">PROMUSICAE</span>) lanzó un “Libro Blanco” sobre la industria musical en España a principios del 2005, aunque la mayoría de las últimas estadísticas contenidas en el libro blanco eran de 2003. La asociación estima que, en el 2003, el 24% de los CDs vendidos en España eran piratas. No hay ningún indicio de que este porcentaje haya cambiado significativamente en el 2004, a pesar de que hubo un mayor volumen de confiscaciones policiales. Más aún, probablemente las descargas por internet aumentaron en el 2004. Los artistas vieron una reducción en las royalties de un 37% entre el 2000 y el 2003, y durante el mismo período los productores de música recortaron el empleo en un 20%. Este es el trasfondo que provoca que los ejecutivos de la industria musical digan que su industria está en “crisis” (entrecomillado en el original). <span class="caps">PROMUSICAE</span> dice que el futuro de la industria depende del desarrollo de nuevos modelos de negocios, tecnologías y futuras legislaciones/aplicaciones. En octubre de 2004, iTunes abrió sus negocios en España, permitiendo a los consumidores que compren música legal online. Las compañías de teléfonos celulares han desarrollado tecnologías permitiendo la descarga (legal) de música digital de calidad. Así, hay algunos desarrollos positivos para la industria musical en 2004. Pero la combinación del mayor nivel de piratería callejera por parte de la UE (que probablemente afecte más a la música, de todas las industrias de la propiedad intelectual) y el desarrollo de los niveles de piratería en Internet del mundo, ha frustrado a la industria de la música. El gobierno habla mucho. De hecho, la ministra de Cultura [Carmen Calvo](http://www.infonoticias.net/modules.php?name=News&file=article&sid=7254) firmó un prólogo para el libro blanco en donde dice que “la administración pública debe ser la garante de los derechos de propiedad intelectual”. Pero traducir incluso niveles relativamente altos de actividad de aplicación de la ley en reducciones significativas del nivel de piratería sigue siendo un reto.

4. **<span class="caps">VIDEOJUEGOS</span>**: Los juegos pirateados siguen disponibles a pesar de que la <span class="caps">IIPA</span> señala que “hubo más acciones de la policía contra los puntos de venta de productos falsificados y pirateados en el 2004”.

5. **<span class="caps">SECTOR</span> <span class="caps">AUDIOVISUAL</span>**: La <span class="caps">IIPA</span> estima pérdidas por 40 millones de doláres. Los <span class="caps">DVD</span>s piratas siguen disponibles en la calle, en las estaciones de subte y en los bares y restaurantes. Un representante de la industria le dijo a Econoff que ha tratado repetidamente de llegar a un acuerdo con la asociación de bares y restaurantes, pero la asociación no devuelve sus llamados. (Comentario: hacer algo al respecto de las ventas rampantes de productos audiovisuales y musicales pirateados en bares y restaurantes deberá ser una prioridad. Este negocio está dominado por **vendedores chinos** que frecuentan establecimientos de clase media y alta para ofrecer sus mercancías.) **La Federación Española para la Protección de la Propiedad Intelectual (<span class="caps">FAP</span>) está también particularmente preocupado por la piratería en internet, dado que el tiempo promedio para descargar una película se reduce a siete minutos con las últimas conexiones <span class="caps">ADSL</span>**.

6. **<span class="caps">SOFTWARE</span>**: La Alianza Comercial de Software (Business Software Alliance, <span class="caps">BSA</span>) estima que en 2004 el nivel de piratería es del 44%, por debaje del 49% estimado en 2003, pero que aún así es uno de los niveles más altos en la Unión Europea. Las pequeñas companías, los distribuidores y los “bajadores” de Internet son los principales perpetradores de la piratería de software.

7. **<span class="caps">ASUNTOS</span> DE <span class="caps">MARCAS</span>**: La embajada no sabe si hay algún tema de marcas afectando a las firmas norteamericanas. Nike todavía sigue comprometida en batallas en la corte con su ex socio [ *former partner* ], pero el aspecto específicamente relacionado con la marca (por ejemplo, quién puede usar la marca) de la compañía, luego de una década de litigio está terminado.

#### <span class="caps">PATENTES</span> FARMACEÚTICAS

8. El problema de las patentes de farmaceúticos de España es un legado de sus viejos procesos de la ley de patentes, que estuvo en efecto hasta Octubre de 1992. A partir de ese momento, todas las patentes farmaceúticas concedidas fueron patentes de productos. **Las compañías farmaceúticas se quejaron de que los productores no-innovadores están habilitados para obtener fácilmente permisos para producir “copias legales” de sus procesos de patentado de drogas si hacen cambios menores en el proceso de producción**. Como otros países que tienen una historia reciente de las patentes de procedimiento [ *process patents* ], este es un problema que sólo el tiempo resolverá. Por los próximos siete años, el legado del viejo sistema de patentes continuará fastidiando a las compañías farmaceúticas, pero hasta que todas las patentes de procedimientos no expiren, no anticipamos un cambio significativo en la situación.

9. Las compañías farmaceúticas norteamericanas operando en España recientemente asumieron posiciones de liderazgo en la asociación farmaceútica de España, Farmaindustria. Las compañías americanas en España están preocupadas respecto de los impuestos gubernamentales y las políticas de precios que afectan a la industria, que quizás tengan un efecto especialmente [ *deleterios?, en el original* ] en la industria basada en R&D [asumo que será I+D]. De hecho, estas políticas son la principal preocupación de las firmas nortamericanas, más que los compromisos claramente relacionados con los derechos de propiedad intelectual y/o relacionados con <span class="caps">ADPIC</span> que ha asumido el <span class="caps">GOE</span>.

#### <span class="caps">ESFUERZOS</span> <span class="caps">POLICIALES</span> DE APLICACIÓN

10. En 2004, la Policía Nacional condujo 982 requisas y 1.304 arrestos, por encima de 488 requisas [ *allanamientos* ] y 733 arrestos en 2003. La policía municipal de Madrid confiscó 1.6 millones de ítems y condujo 390 allanamientos en 2003. La policía municipal confiscó a duras penas 1.2 millones de ítems en 2004 y condujo 256 allanamientos en 2004, un [ *downtick. Desconozco el significado de esta palabra* ]. Actualmente no tenemos números de otras entidades de aplicación [ *de la ley* ]. Lo importante de destacar de estos niveles de aplicación de la ley, de hecho bastante impresionantes, es que sin embargo **no tienen un efecto significativo de disuasión**. Probablemente esto sea debidado a que muy pocas condenas resultaron en sentencias de cárcel signficativas y/o multas. La mayoría de los arrestados son liberados luego de unos días y se les da una audiencia de corte para meses después. Para los piratas, la aplicación policial es realmente un costo menor de hacer negocios. En teoría, el código penal más duro (efectivo desde el 1 de octubre de 2004) le da a la policía las herramientas para ir detrás de los piratas ex-oficio. Y los jueces tienen la opción de dar sentencias más rígidas. **Pero en la práctica, la falta de interés por parte de las cortes en crímenes de derechos de propiedad intelectual, complica el esfuerzo de montar una campaña de aplicación [ *de la ley* ] significativa**.

#### <span class="caps">ESFUERZO</span> <span class="caps">EDUCACIONALES</span>

11. En enero de 2005, la ministra de Cultura Carmen Calvo participó en un evento llamado “Días de Entrenamiento para Profesionales Expertos en el Estudio de material Fonográfico y Videográfico”. Este fue un evento mayor que recibió una cobertura de prensa extensa, y se enfocó en la piratería. En mayo de 2004, España asistió a una conferencia de la Interpol y la <span class="caps">WCO</span> (World Customs Organization) sobre falsificación.

#### <span class="caps">INICIATIVA</span> <span class="caps">ANTI</span> PIRATERÍA

12. El ministerio de Cultura anunció el 29-12-2004 el “Plan Integral para la Reducción y Eliminación de las Actividades Violatorias de la Propiedad Intelectual” del <span class="caps">GOE</span>. El plan, que todavía está en proceso de finalización y en consulta con la industria, involucra la coordinación de once ministerios diferentes, en un esfuerzo por reducir la piratería. El Secretario del Ministerio de Cultura (Under Secretary) Antonio Hidalgo le contó en una visita al Secretario Asistente de Comercio William H. Lash, <span class="caps">III</span>, el 17-02-2005 (septel) que el hecho de que el Ministerio de Cultura haya logrado reunir 11 ministerios en colaboración para luchar contra la piratería, **demostraba que Zapatero en persona estaba interesado en el tema** —de lo contrario, la mayoría de los ministerios no estarían interesados en participar. El plan involucra crear una Comisión Interadministrativa para coordinar la protección de los derechos de propiedad intelectual; describir el problema de la piratería en todos sus aspectos; concudir campañas públicas de educación; **refromar la legislación y el marco regulatorio**; y un entrenamiento judicial y en aplicación de la ley. (Comentario: algo de este trabajo es probablemente redundante, pero aún así vale la pena, sobre todo notando que los sectores más relevantes de la industria están cooperando con el gobierno en esta iniciativa).

#### <span class="caps">PROPUESTA</span> DE <span class="caps">MESA</span> <span class="caps">REDONDA</span> <span class="caps">SOBRE</span> <span class="caps">DERECHOS</span> DE <span class="caps">PROPIEDAD</span> <span class="caps">INTELECTUAL</span> <span class="caps">ENTRE</span> ESPAÑA-<span class="caps">EEUU</span>

13. El Secretario Asistente del Departamento de Comercio Lash y el [ *Deputy Assistan Secretary* ] Eric Stewart condujeron reuniones con representantes de la industria, el Ministerio de Industria, Turismo y Comercio, el Ministerio de Cultura y el de Política Nacional [ *National Policy* ] el 17 de febrero. Lash propuso la organización de una mesa redonda sobre derechos de propiedad intelectual entre US-España en algún momento del 2005. Todos los interlocutores del <span class="caps">GOE</span> en principio aceptaron. El Ministerio de Cultura probablemente tome el liderazgo por el <span class="caps">GOE</span> en este evento.

#### SE <span class="caps">NECESITAN</span> <span class="caps">ARREGLOS</span> <span class="caps">LEGISLATIVOS</span>/REGULATORIOS

14. Los <span class="caps">ISP</span> (Internet Service Providers, Proveedores de Servicios de Internet) sólo están obligados a tomar acciones contra los piratas si tienen “conocimiento efectivo” de la piratería. La ley de e-comercio de España define dos formas de que los <span class="caps">ISP</span> tengan “conocimiento efectivo”. **Una orden de la corte puede proveer semejante conocimiento, pero conseguir una orden es tiempo consumido**. La ley española de e-comercio también provee la posibilidad de usar un mecanismo administrativo, pero los proveedores de contenido no tienen claro cómo pueden aprovechar ellos este mecanismo. Oficiales del Ministerio de Cultura le dijeron A/S Lash que trabajarán en **clarificar la ruta administrativa sobre proveer de “conocimiento efectivo” a los proveedores de Internet**. Dicen que esto puede ser hecho a través de la regulación, más que legislativamente. Esto de un enorme interés práctico para, por ejemplo, la industria musical. En España, el <span class="caps">ISP</span> más importante es Telefónica. La industria se queja de que el ambiente legal actual no provee el incentivo suficiente para que **las grandes telcos repriman** [ *clamp down* ] a los piratas. Dado que la “aplicación matadora” (por ejemplo, la más vendida) en el mundo de la internet es un programa que permite descargar música, la frustración de la industria en este asunto va en aumento.

15. La ley que traspone la Directiva de Copyright de la EU contiene dos serias debilidades, según los representantes de la industria. Primero, define el copiado muy estrechamente. El borrador actual dice que copiar es fijar [ *o poner en fijación* ] una obra, de modo tal que pueda ser comunicada y copiada. La industria quiere una definición de copiar. **La industria también quiere que el copiado permitido por el uso privado sea limitado** y que los copiadores **no puedan superar los dispositivos contra la elusión [ *como el <span class="caps">DRM</span>* ]**.

#### ÁREAS DE REVISIÓN EN <span class="caps">CURSO</span>

16. **<span class="caps">REGULACIONES</span> <span class="caps">SOBRE</span> PIRATERÍA <span class="caps">CON</span> <span class="caps">MEDIOS</span> ÓPTICOS**: El artículo 25 de la legislación española sobre propiedad intelectual establece un impuesto [ *tax: en inglés “tax” es en efecto “impuesto”, pero lo cierto es que el canon no cumple algunos de los requisitos necesarios para poder ser considerado un impuesto, por ejemplo, no es el Estado quien lo recauda, sino una entidad privada, por lo que en realidad estaríamos hablando de un canon* ] en la manufactura de equipamientos ópticos; se les solicita a los operadores aplicar para conseguir licencias. No hay ninguna legislación que requiera que los <span class="caps">SID</span> (códigos de identificación de fuentes) sean usados en CDs manufacturados localmente. A pesar de esto, **12 de 13 productores de discos compactos han firmado acuerdos de <span class="caps">SID</span> con Phillips e <span class="caps">IFPI</span>.**

17. **<span class="caps">USO</span>/CONTRATACIÓN DE <span class="caps">SOFTWARE</span> <span class="caps">PARA</span> EL <span class="caps">GOBIERNO</span>**: Como ha sido reportado previamente, en el año 2000 el <span class="caps">GOE</span> publicó directrices tituladas “La propiedad intelectual de los programas de software”. Estas directrices son para los ministerios de gobierno y delimitan medidas, recomendaciones y buenas prácticas para adquirir y utilizar software. Las directrices han sido explicadas en workshops y están ampliamente disponibles para los oficiales del gobierno español, incluso en Internet.

18. **<span class="caps">CUMPLIMIENTO</span> DE <span class="caps">ADPIC</span>**: El <span class="caps">GOE</span> se cuenta en completo cumplimiento con <span class="caps">ADPIC</span> (<span class="caps">TRIP</span>: Trade Related Aspects of Intellectual Property, Acuerdos sobre los Aspectos de Propiedad Intelectual Relacionados con el Comercio) desde 1997.

19. **APLICACIÓN**: Ver párrafo 9 arriba.

#### <span class="caps">COMENTARIO</span>

20. **La pintura de la piratería española sobre los derechos de propiedad intelectual es una amalgama entre el Tercer Mundo y el Primer Mundo**. Productos pirateados fácilmente disponibles en la calle, en las estaciones de subte, bareas y restaurantes, parece una rememoración del Tercer Mundo. Los niveles de piratería en Internet se acercan a los países más avanzados del mundo. Claramente, este gobierno se toma el asunto en serio, pero llevará educación sostenida, aplicación de la ley y esfuerzos legislativos y regulataros para traer la piratería a bajos niveles. En balance, creemos que este gobierno debe tener otro año fuera de la Lista de Vigilancia para trabajar sobre la piratería de los derechos de propiedad intelectual. Pero no importa lo que pasa respecto de la inclusión o no de España, la Embajada de Madrid instará al <span class="caps">GOE</span> para que se concentre en las siguientes acciones.

A. Un nivel apropiado de participación en una mesa redonda sobre derechos de propiedad intelectual entre España y <span class="caps">EEUU</span>.

B. **La creación de un mecanismo administrativo efectivo para compelir a los <span class="caps">ISP</span>s de que desconecten a los piratas**.

C. Arreglos legislativos a la ley propuesta para la Directiva de Copyright de la UE.

D. **Trabajar con las asociaciones de bares/restaurantes para mantener alejados a los piratas de dichos establecimientos**. Trabajar también con las autoridades del subte.

**Dada la abierta preferencia por el gobierno socialista de parte de muchas estrellas de la industria del entretenimiento** (es significativo, por ejemplo, que Zapatero haya atendido al equivalente español de los Oscars), es posible que **este gobierno sea especialmente sensible a hacer algo por este sector**. Necesitamos un año o algo así para ver si esta sensibilidad se traduce en resultados.

<span class="caps">MANZANARES</span>


* * * * *

más cables traducidos en

[Cables sobre Propiedad Intelectual en Wikileaks](/blog/2010/12/cables-wikileaks-propiedad-intelectual.html)





