---
title: 'Bienvenidos al Dominio Público: James Joyce (II)'
author: derechoaleer
created: !!timestamp 2012-01-10 15:35:34
tags: 
    - Autores
    - Dominio público

comments: 2
nid: 426
order: 358
type: story
status: 1
format: 2
comments_status: open
---

{% mark excerpt -%}

<span class="img">![Joyce y Sylvia Beach](/media/img/2012/joyce/joyce-y-sylvia-beach.jpg)
<span class="ep">Paris, 1920. James Joyce junto a la editora Sylvia Beach. afuera de la librería "Shakespeare and Company" en Rue de l'Odeon.[\[fuente\]](http://www.phorum.gr/viewtopic.php?t=91408)</span></span>

Suele alimentarse el mito de que el derecho de autor es el principal medio de subsistencia económica de los "creadores". Lejos de esa afirmación interesada, [el hecho es más bien una excepción](/blog/2009/09/de-que-no-viven-los-escritores.html), en particular, si nos referimos al campo literario. Los escritores célebres no escapan a la regla, y James Joyce, quizá **el escritor más importante del siglo XX**, seguramente habría quedado fascinado por un invento como internet. Y no estamos especulando aquí con las [implicancias estéticas y conceptuales del *hiperenlace*](http://wiretap.area.com/Gopher/Library/Cyber/joyce.txt), sino con algo mucho más prosaico: **las posibilidad de eludir la censura y de publicar fácilmente**.

### Crowdfunding

Siete años le llevó a Joyce escribir el Ulises. Para 1921 ya lo tenía terminado y era **un escritor reconocido entre el círculo modernista**. Sin embargo Joyce y su familia solían pasar penurias económicas por esos años. Los recursos monetarios que le permitían dedicar tiempo a escribir **no provenían de la industria editorial**: el escritor trabajaba dando clases y escribiendo artículos para revistas, además de recibir ayuda económica de sus amigos y familiares. ["Las ventas han caído en picado desde el inicio de la guerra"](http://markos-blogdehistoria.blogspot.com.ar/) le respondía el editor de *"Dublineses"*... respuesta imposible de corroborar para el autor, como es sabido.

En contraste, un "benefactor anónimo" decidió ingresar la cantidad de mil francos mensuales a sus cuentas, durante 1918. No fue el único<sup><a href="#fn-1" id="bn-1">1</a></sup>. Como siempre, **los interesados en que un autor escriba son los primeros en proporcionar apoyo financiero**, aunque en ese grupo generalmente [no están los editores, más bien los lectores](/blog/2011/12/casciari-los-lectores-y-los-autores-y-nadie-mas.html). Cuando Joyce y su editora tuvieron al fin el libro listo para publicar, recurrieron a un viejo conocido para obtener financiación: el *crowdfunding*, y vendieron mil suscripciones<sup><a href="#fn-2" id="bn-2">2</a></sup>, antes de tener impreso el libro.

Este escritor, como diría Roberto Arlt, no disponía [<q>de rentas, tiempo o sedantes empleos nacionales</q>](/blog/2009/09/de-que-no-viven-los-escritores.html), para poder escribir. La familia de Joyce —y toda Irlanda— habían quebrado antes de que James llegara a la adolescencia, y desde entonces, no tuvo más remedio que procurarse él mismo sus propios recursos para poder escribir: docente, empleado, periodista, su nomadismo por Europa también respondió a la necesidad de conseguir mejores ofertas laborales.

### Joyce banned

Además de la falta de financiamiento, otro pertinaz perseguidor se ensañó con las obras de Joyce desde el inicio: **la censura**. 

Ya con *'Dublineses'*, Joyce tuvo dificultades con los editores irlandeses y la censura. Luego, por años estuvo ofreciendo fragmentos del manuscrito del Ulises a decenas de editores, incluso a la ahora mítica "Hogarth Press" de Leonard y [Virginia Woolf](/blog/2011/12/bienvenidos-al-dominio-publico-virginia-woolf.html), que rechazó la oferta. 

Las consecuencias de publicar un libro que pudiera ser considerado "obsceno", en la década del 20, no se limitaban al escandalo de, por ejemplo, [suspender una entrega de premios](http://old.clarin.com.ar/diario/96/11/21/E-05001d.htm)... **Hasta el linotipista podía recibir sanciones serias, multas o la cárcel**, por componer un texto considerado "indecente". Este método para hacer efectiva la censura, castigando responsabilidades indirectas, sigue [completamente vigente](/blog/2011/11/infografia-otra-vez-sopa.html). El truco está en apuntar las amenazas legales a los eslabones menos comprometidos con la publicación del material sensible: desde el impresor al linotipista antes, al administrador de un foro o proveedor de internet ahora. Es muy probable que ninguno de esos actores estén dispuestos a correr los mismos riesgos que el autor, más visceralmente comprometido con la publicación de su propia obra. 

La fallida publicación de *Dublineses* en Irlanda, es un buen ejemplo de la efectividad de esta estrategia:

> <q>[...] Durante su estancia en Dublín, Joyce hizo un último y desesperado esfuerzo para publicar Dublineses en Maunsel & Co. Aceptó a regañadientes eliminar «An Encounter», una historia sobre el ambiguo encuentro entre un escolar y un pederasta, y acordó con indemnizar al editor con el costo de la primera edición en caso de a ser incautada por la policía. Pero Georges Roberts, el cauteloso gerente Maunsel & Co., luego formuló una nueva serie de quejas en contra el libro: exigió a Joyce cambiar el primer párrafo de  «Grace», tres párrafos de «Ivy Day», secciones de «The Boarding House», y cada nombre propio de las historias contenidas. Al recibir la furiosa negativa de Joyce a cumplir con estas demandas, Roberts le sugirió comprar las matrices de Dublineses por £50 e imprimirlo el mismo. Joyce aceptó la idea, pero el impresor de Roberts intervino, negándose a entregar matrices que contenían material tan difamatorio para Irlanda. Todo el asunto llegó a su conclusión el 11 de septiembre 1912, cuando el impresor sumariamente destruyó las planchas antes que Joyce pudiera reclamar. Desolado y furioso, Joyce salió de Irlanda esa misma noche, para no volver nunca.</q><sup><a href="#fn-3" id="bn-3">3</a></sup>


{%- endmark %}


Algunos editores de revistas literarias, movidos más por la admiración y el esnobismo que por el negocio, **se animaron a publicar el Ulises por entregas**<sup><a href="#fn-4" id="bn-4">4</a></sup>. En Estados Unidos Margaret Caroline Anderson, editora de la revista [*"The Little Review"*](http://www.google.com.ar/search?q=The+Little+Review&tbm=isch), tuvo que recurrir [a un linotipista *serbocroata*](http://es.wikipedia.org/wiki/Ulises_%28novela%29#Publicaci.C3.B3n). En Inglaterra, Harriet Shaw Weaver, de la revista <a href="http://en.wikipedia.org/wiki/The_Egoist_(periodical)">*"The Egoist"*</a>, paso un año buscando un tipógrafo que estuviera dispuesto a correr el riesgo. La edición completa del Ulises se publicó finalmente en París, en 1922. La editora [Sylvia Beach](http://en.wikipedia.org/wiki/Sylvia_Beach) de la librería *Shakespeare & Co*, especializada en obras en idioma inglés en Francia y frecuentada por muchos escritores e intelectuales que admiraban a Joyce, asumió el desafío. Además de ser la primera publicación del Ulises completo, la edición **fue célebre por sus erratas**: era conveniente que los linotipistas franceses no entendieran del todo, lo que estaban componiendo.

### Mail Filtering

La suerte del Ulises por entregas en Estados Unidos se acabó pronto. Cuando llegó al Episodio 13 "Nausícaa", la masturbación de Leopold Bloom fue demasiado. A pesar de que la revista *"The Little Review"* **se distribuía por correo**, el medio no la hacia inmune a la censura. 

<span class="float" style="width:300px;">![logotipo de 'New York Society For The Suppression Of Vice'](/media/img/2012/joyce/NewYorkSocietyForTheSuppressionOfVice.jpg)<span class="ep" style="margin: 1em 0 0;">La "Sociedad para la Prevención del Vicio de Nueva York", institución dedicada a la supervisión de la moralidad pública que mantuvo el Ulises alejado del público estadounidense por más de diez años [imagen [wikimedia](http://en.wikipedia.org/wiki/File:NewYorkSocietyForTheSuppressionOfVice.jpg)]</span></span> Aunque ahora pudiera resultar escandaloso, a principio de siglo la oficina de correos, al igual que la de aduanas, tenía **la potestad de abrir los sobres e incautar material** que pudiera considerar ofensivo y obsceno en Estados Unidos<sup><a href="#fn-5" id="bn-5">5</a></sup>, incluso de la privadísima correspondencia. La ["Sociedad para la Prevención del Vicio de Nueva York"](http://en.wikipedia.org/wiki/New_York_Society_for_the_Suppression_of_Vice), que tenia un sello identificatorio por demás elocuente, obligó a la revista a abandonar la publicación de la novela. Los editores de la revista tuvieron que someterse a un vergonzoso proceso policial, y dejar sus huellas digitales registradas, como delincuentes. En Inglaterra, *"The Egoist"* también tuvo que suspender la entrega periódica por motivos similares. Luego de la publicación del libro en Francia, los intentos de importación a los países de habla inglesa resultaron igualmente infructuosos, literalmente, **ardían en las aduanas**. Los únicos ejemplares que ingresaron a Estados Unidos o Inglaterra en esos años, lo hicieron de contrabando, en el equipaje de viajeros.

### United States v. One Book Called Ulysses

Puede parecer un título metafórico, [pero no lo es](http://en.wikipedia.org/wiki/United_States_v._One_Book_Called_Ulysses). Ese nombre identificó **la causa judicial que finalmente terminó con la censura del Ulises, luego de 16 años de "banneo" total en Estados Unidos**. 

El último intento de publicación lo había realizado el controvertido editor de literatura erótica [**Samuel Roth**](http://en.wikipedia.org/wiki/Samuel_Roth), claro que sin autorización de Joyce --que lo último que deseaba ver, era su obra circulando en ese ambiente. El hecho enfureció al escritor, que escribió una [**carta pública de protesta**](http://books.google.com.ar/books?id=4yrBZ7FkXRkC&lpg=PP1&hl=es&pg=PA191#v=onepage&q&f=false), acompañada por la firma de otros varios escritores conocidos. La carta persuadió a Roth de abandonar el proyecto. Sin embargo **no se trataba de un libro "pirata" o ilegal**: según las leyes de aquel momento, pasados algunos meses desde la publicación de una obra en el extranjero, --y en 1926 habían pasado 4 años-- si no se publicaba una edición impresa en Estados Unidos y se registraba en la oficina de *copyright* (y el fuego de la aduana y el correo habían hecho imposible que tal trámite se produjese), la obra quedaba en dominio público. Cabe mencionar que Roth de todas formas envió un cheque por regalías, que Joyce rechazó.

Pero la carta de protesta también sirvió para abrir el debate sobre **la censura del libro de Joyce**. Algunos amigos suspicaces de Joyce sugirieron que su editora, Sylvia Beach de la librería Shakespeare & Co, se había <q>sentado sobre los derechos de Joyce</q> y cerraba las puertas a la edición norteamericana, para no competir con la europea. Ofendida, Beach, renunció a los derechos del *Ulysses* y permitió que Joyce iniciara conversaciones más decididas con editores norteamericanos.

<span class="float">![Joyce en la revista Times](/media/img/2012/joyce/joyce-times-200.jpg)</span> [Bennett Cerf](Bennett Cerf), el fundador de Random House (y si! primo lejano del [inventor de internet](http://es.wikipedia.org/wiki/Vinton_Cerf)), accedió a dar la batalla legal, y **planificó una estudiada estrategia para convertir la causa en un caso testigo**. Importó los libros esperando que fueran incautados por la aduana y dio inicio a las acciones judiciales. El fallo del Juez John M. Woolsey, **terminó con la censura sobre Ulises en 1934**. Un tribunal de apelación, confirmó la sentencia de Woolsey y la noticia llegó a tapa de Times. El juez fijó un nuevo estándar judicial al considerar casos de "obscenidad" --tomado incluso como referencia por la Corte Suprema. Estableció tres directrices: i) que la obra debía ser evaluada completa, no sólo por un fragmento aislado; ii) que debía considerarse a una persona "promedio", y no una "sensible" al momento de evaluar su impacto; iii) que debía tomarse el concepto de obscenidad según los estándares de la época. Hubo que llegar los 70' para que la Corte Suprema estadounidense determinada que la obscenidad estaba protegida también por la primera enmienda y no podía censurarse, mientras no se expusiera a menores o terceras partes.

Llegado el nuevo milenio, no estaría de más recordarle a la empresa [**Apple**](/blog/2010/01/un-millon-de-moscas-no-pueden-eq.html) esta última definición de la corte. Haciendo honor a la tradición puritana estadounidense la empresa de cupertino sigue a rajatabla una especie de **cruzada moralista**, decidiendo qué aplicaciones (y por ende qué publicaciones) pueden integrarse a su plataforma. Siguiendo el ejemplo de la "Sociedad para la Prevención del Vicio de Nueva York", [**Apple bannea contenidos que considera "indecentes"**](http://www.switched.com/2010/06/14/apple-says-james-joyce-is-too-obscene-for-the-app-store/). El colmo del banneo fue nada menos que [**un comic Robert Berry**](http://ulyssesseen.com/), adaptación de un clásico de la literatura... que, ironías del destino, no podía ser otro que el *Ulysses* de James Joyce. Por el escándalo, Apple [finalmente consideró](http://www.nytimes.com/2010/06/14/technology/14ulysses.html?partner=rss&emc=rss) que el comic en realidad "no era obsceno" y "lo autorizó". 

<span class="centrado"><span style="width:400px;">[![Really? Again?](/media/img/2012/joyce/ipad_joyce.jpg)](http://www.switched.com/2010/06/14/apple-says-james-joyce-is-too-obscene-for-the-app-store/)<span class="ep"><a href="http://www.publico.es/ciencias/306812/jobs-responde-si-quieres-porno-comprate-un-android"><q>Si quieres porno comprate un Android</q></a>, lo dijo Steve Jobs.</span></span></span>

### Copyright "de cortesía"

Una vez dictaminado el fallo, lo primero que hicieron los editores fue registrar el Ulises en la oficina de *copyright* estadounidense. Pero como ya mencionamos este registro fue completamente inválido. La obra ya se había publicado, en inglés y en el extranjero hacía años, por lo tanto estaba en dominio público. Las demás editoriales conocían este hecho, sin embargo **no hubo ediciones paralelas del Ulises** ¿por qué? la carta de Joyce contra el editor Roth acompañada de la firma de multitud de escritores, recordaba a los editores que sin el aval del autor, difícilmente una edición pudiera tener éxito entre sus lectores, al menos en libros que no eran masivos y que tenían un público bien definido, como era el caso de los modernistas. Por lo tanto se estableció un insólito *"copyright de cortesía"* otorgado por las otras editoriales, al menos hasta 1994. En ese año, una enmienda a la ley norteamericana otorgó **en forma retroactiva** el *copyright* a <q>las obras que no hubieren cumplido las formalidades de registro</q>, como era el caso del Ulises. De esta forma, siete décadas después de su publicación, el libro pasó a tener *copyright* genuino, hasta su entrada en dominio público, que debería haber ocurrido en 1998. Pero la cuestión no termino ahí.

En el 1998, se aprobó la nefasta [*Mickey Mouse Copyrigth Act*](http://en.wikipedia.org/wiki/Copyright_Term_Extension_Act), que extendió los plazos aún más. Pero para la herencia de Joyce, eso no era suficiente, y pretendió establecer como fecha de registro la de 1934, con lo cual [el Ulises entraría en dominio público ¡recién en 2030!](https://joycefoundation.osu.edu/joyce-copyright/fair-use-and-permissions/about-law/public-domain)

En [*"Copyright Protectionism and Its Discontents: The Case of James Joyce's «Ulysses» in America"*](/media/files/Spoo-Robert-Ulysses-in-america.pdf) el académico Robert Spoo advertía, en 1998, sobre los efectos de extender el monopolio de la obra máxima de Joyce:

> Los efectos del monopolio continuarán haciéndose sentir: Los lectores pagarán precios no competitivos por las ediciones de Ulises autorizadas por la herencia de Joyce, los académicos se verán desalentados en producir versiones alternativas de la novela en formato impreso y electrónico de texto. En particular, los beneficios del ciberespacio y la digitalización se perderán o se silenciarán en lo que a Ulises se refiere. A pesar de que los autores del modernismo como Joyce, en general, tienen un público limitado, la evidencia reciente sugiere que el monopolio de los derechos de autor artificialmente deprime el mercado de la literatura modernista. Cuando la oferta de las obras difíciles, aumenta en cantidad y disminuye en precio, puede resultar que la demanda del lector no especializado, se incremente.

La variable y compleja telaraña de legislaciones sobre los plazos de *copyright* en el mundo, hace difícil sostener concluyentemente que "Joyce ya ha entrado el dominio público en 2012". Hay matices. La primer edicion de Ulises de 1922, por ejemplo, oficialmente ya está en dominio público en todo el mundo, pero [según el sitio de Joyce Foundation](https://joycefoundation.osu.edu/joyce-copyright/fair-use-and-permissions/about-law/public-domain), muchas de sus obras siguen en dominio privado en algunos países, incluso hasta la séptima década de este siglo. 

Habrá que esperar.

* * * * *

La tercera parte de esta serie: las desventuras de [Stephen Joyce](http://es.wikipedia.org/wiki/Stephen_Joyce), el inefable nieto de James Joyce, próximamente...


* * * * * 


### Notas

<div class="notas" markdown="1">

[<span id="fn-1">1</span>] <q>[...] Sin embargo, Joyce fue rescatado luego por cierta misteriosa buena fortuna, que siempre parecía presentarse cuando había llegado a su punto más bajo. Un benefactor anónimo le hizo una donación de £ 200 en cuatro cuotas, y luego en agosto recibió la noticia de que Richards había accedido finalmente a publicar Exiles. Un año después, la primer donación fue complementada por otro otorgamiento anónimo de la nada despreciable suma de casi 1.000 francos suizos (aproximadamente £ 40) por mes; este patrocinio comenzó en marzo de 1918 y continuó durante unos dieciocho meses. Curioso en cuanto a la identidad de sus misteriosos benefactores, Joyce finalmente estableció que en el segundo caso, se trataba de la señora Harold McCormick, actriz y considerada una de las mujeres más ricas de Zurich.</q> Y luego en 1919: <q>La pérdida de patrocinio señora McCormick le dejó a Joyce mayores restricciones financieras, a pesar de que antes de salir de Zurich su situación había mejorado considerablemente por la llegada de otro benefactor anónimo. En un telegrama un abogado le informó a Joyce que un cliente no identificado deseaba otorgarle alrededor de 5.000 libras, beneficio que iba a mantenerse durante varios meses. Antes de finalizar, Joyce descubrió que se trataba de su amiga y admiradora Harriet Weaver. El dinero, sin embargo, tenía la mala costumbre de esfumarse de las manos de Joyce. Para asegurarse la apariencia de un ingreso estable, Joyce regresó a su puesto anterior de profesor en la Scuola Superiore di Commercio Revoltella</q> ["James Joyce: A Critical Guide"](http://books.google.com.ar/books?id=xznjIaZC3nkC&hl=es), por Lee Spinks, [pág. 32 y 34](http://books.google.com.ar/books?id=xznjIaZC3nkC&lpg=PP1&hl=es&pg=PA34#v=onepage&q&f=false). <a href="#bn-1">↩</a>

[<span id="fn-2">2</span>] <q>Para ayudar a la financiación del libro, se buscaron mil subscriptores de una primera edición de lujo, cuya lista incluía nombres tan curiosos como el de Winston Churchill. En cambio Bernard Shaw, después de contestar a la petición haciendo un gran elogio de lo que había leído de Joyce, concluía «Pero no conoce usted lo que es un irlandés, y de edad, si cree que está dispuesto a pagar 150 francos por un libro»</q> "Ulises", traducción de Jose Mª Valverde (1976), pag. 32. <a href="#bn-2">↩</a>

[<span id="fn-3">3</span>] Lee Spinks "James Joyce: A Critical Guide", pag. 28 parcialmente disponible en [Google Books](http://books.google.com.ar/books?id=xznjIaZC3nkC&lpg=PP1&hl=es&pg=PA28#v=onepage&q&f=false). <a href="#bn-3">↩</a>

[<span id="fn-4">4</span>] <q>Harriet Shaw Weaver, despreciando su propio riesgo, hubo de pasar un año buscando tipógrafo hasta que encontró uno que se atrevió a imprimir --y eso con algunos cortes-- los capítulos [2], [3], [6], y [10] (El matrimonio Virginia/Leonard Woolf rechazó la oferta de ser coeditores e impresores, en su prensa de mano de la Hogarth Press). Para entonces Joyce impaciente ya había recurrido a Ezra Pound, con la esperanza de hallar más libertad en Estados Unidos. Pound envió los tres primeros capítulos a la "Little Review", nacida en Chicago en 1914 y recién transladada a Nueva York bajo la inspiración de Margaret Anderson, quien apenas leyó el primer párrafo del capítulo [3], dijo «lo imprimiremos aunque fuera el ultimo esfuerzo de nuestra vida». Pero tampoco fue fácil encontrar un tipógrafo igualmente entusiasta. Al fin un serbocroata insensibe a los atrevimientos verbales del inglés, se prestó a ello. Lo malo de la publicación por capítulos en las revistas, era que si una sola de las entregas era condenada, ya no podía publicarse el libro en su integridad, pero Joyce desoyó el prudente consejo de abandonar la serialización, y reservar toda la batalla para el libro entero una vez acabado. Y en efecto, los censores del correo [...] no tardaron en caer sobre la minoritaria revistilla, confiscando y quemando los números donde iban los capítulos [8], [9] y [12]. Si el lector observa de cuáles se trata --sobre todo [9] y [12]-- se asombrará de tal quema: el caso del [8] es especialmente interesante, porque, aparte de algún ensueño erótico de Bloom, lo que escandalizó debe ser la crudeza con que se pinta el acto de comer y beber, amén de las ventosidades finales. Joyce, cuyos inocentes Dublineses ya habían ardido inéditos en su primera edición, comentó: «es la segunda vez que me queman en este mundo, asi que espero pasar por el fuego del purgatorio tan de prisa como mi patrono San Luis Gonzaga». Pero aun hubo algo peor: el capítulo [13], con exhibicionismo distante de ropa interior de Gerty MacDowell, fue denunciado por la Sociedad para la Prevención del Vicio de Nueva York, y, a pesar de brillantes defensas de orden literario, fue condenado a multa y abandono de la publicación</q>. *Ulises*, prólogo de José María Valverde a la edición en español de 1976. <a href="#bn-4">↩</a>

[<span id="fn-5">5</span>] <q>Entre enero de 1919 y enero de 1920, las autoridades de la oficina de correos suprimieron tres números diferentes, cada uno con una parte de la novela de Joyce, revocando los privilegios de franqueo de la revista The Little Review [...] Ya habían sido declaradas no franqueables una vez, en octubre de 1917, cuando el Jefe de Correos de la Ciudad de Nueva York decidió que una historia corta por el autor modernista Wyndham Lewis era «obsceno, ofensivo o lascivo» dentro de lo previsto por el Código Penal Federal.</q> ["Copyright Protectionism and Its Discontents: The Case of James Joyce's «Ulysses» in America"](/media/files/Spoo-Robert-Ulysses-in-america.pdf) por Robert Spoo. p. 637. <a href="#bn-5">↩</a>

</div>

