---
title: 'Public Domain Day 2012!'
author: derechoaleer
created: !!timestamp 2012-01-01 15:14:33
tags: 
    - Autores
    - Dominio público

comments: 2
nid: 424
order: 356
type: story
status: 1
format: 5
---

{% mark excerpt -%}

<div>


<span class="img"><img src="/media/img/2012/public_domain_day_2012-poster.jpg" usemap="#map"/></span>
<map name="map">
<!-- #$-:Image map file created by GIMP Image Map plug-in -->
<!-- #$-:GIMP Image Map plug-in by Maurits Rijk -->
<!-- #$-:Please do not edit lines starting with "#$" -->
<!-- #$VERSION:2.3 <!-- #$AUTHOR:bond -->
{% if _markings_ is defined -%}
<area shape="poly" coords="71,135,129,22,349,232,117,169" alt="El Lissitzky" href="/blog/2012/01/public-domain-day-2012.html#El_Lissitzky" />
<area shape="poly" coords="149,223,99,266,138,319,194,272" alt="Marina Tsvetaeva" href="/blog/2012/01/public-domain-day-2012.html#Marina_Tsvetaeva" />
<area shape="poly" coords="79,162,7,202,28,223,42,278,89,283,101,233,118,222,102,182" alt="Sir Robert Baden-Powell" href="/blog/2012/01/public-domain-day-2012.html#Baden-Powell" />
<area shape="poly" coords="74,316,25,329,28,398,69,460,102,391,115,337" alt="Jelly Roll Morton" href="/blog/2012/01/public-domain-day-2012.html#Jelly_Roll_Morton" />
<area shape="poly" coords="179,320,113,461,242,481,238,457,250,407" alt="Robert Delaunay" href="/blog/2012/01/public-domain-day-2012.html#Robert_Delaunay" />
<area shape="poly" coords="35,702,33,607,23,579,70,522,123,527,171,612,108,659,94,721" alt="Rabindranath Tagore" href="/blog/2012/01/public-domain-day-2012.html#Rabindranath_Tagore" />
<area shape="poly" coords="327,616,282,569,245,558,233,519,258,501,245,470,297,420,332,455,353,445,387,485,353,526,357,559,353,570" alt="James Joyce" href="/blog/2012/01/public-domain-day-2012.html#James_Joyce" />
<area shape="poly" coords="338,363,342,320,381,283,405,281,438,315,443,358,420,420,409,442,374,435,357,394,349,372" alt="Virginia Woolf" href="/blog/2012/01/public-domain-day-2012.html#Virginia_Woolf" />
<area shape="poly" coords="456,513,440,434,460,409,487,399,533,409,544,459,533,489,514,503,482,527" alt="Henri Bergson" href="/blog/2012/01/public-domain-day-2012.html#Henri_Bergson" />
{% else %}
<area shape="poly" coords="71,135,129,22,349,232,117,169" alt="El Lissitzky" href="#El_Lissitzky" />
<area shape="poly" coords="149,223,99,266,138,319,194,272" alt="Marina Tsvetaeva" href="#Marina_Tsvetaeva" />
<area shape="poly" coords="79,162,7,202,28,223,42,278,89,283,101,233,118,222,102,182" alt="Sir Robert Baden-Powell" href="#Baden-Powell" />
<area shape="poly" coords="74,316,25,329,28,398,69,460,102,391,115,337" alt="Jelly Roll Morton" href="#Jelly_Roll_Morton" />
<area shape="poly" coords="179,320,113,461,242,481,238,457,250,407" alt="Robert Delaunay" href="#Robert_Delaunay" />
<area shape="poly" coords="35,702,33,607,23,579,70,522,123,527,171,612,108,659,94,721" alt="Rabindranath Tagore" href="#Rabindranath_Tagore" />
<area shape="poly" coords="327,616,282,569,245,558,233,519,258,501,245,470,297,420,332,455,353,445,387,485,353,526,357,559,353,570" alt="James Joyce" href="#James_Joyce" />
<area shape="poly" coords="338,363,342,320,381,283,405,281,438,315,443,358,420,420,409,442,374,435,357,394,349,372" alt="Virginia Woolf" href="#Virginia_Woolf" />
<area shape="poly" coords="456,513,440,434,460,409,487,399,533,409,544,459,533,489,514,503,482,527" alt="Henri Bergson" href="#Henri_Bergson" />
{% endif %}
</map>

</div>

[\[Agrandar/Enlarge\]](/media/img/2012/public_domain_day_2012-poster.jpg "click to enlarge")

### ¡Feliz Día del Dominio Público 2012!

Como todos los 1º de Enero de cada año se celebra en todo el mundo el [Día del Dominio Público](http://www.publicdomainday.org), la fecha en la cual los autores muertos hace 70 años, ingresan al [Dominio Público](http://es.wikipedia.org/wiki/Dominio_público). Llamado ["páramo", o incluso "piratería legal"](/blog/2010/12/feliz-dia-del-dominio-publico.html#fn_pdd-1) por los enemigos de la cultura, el dominio público es **el acervo común de las obras que retornan al patrimonio colectivo**. El concepto adquiere mayor relevancia, en la medida que las tecnologías digitales posibilitan que las obras en dominio público, puedan convertirse cabalmente en un recurso a ser masivamente socializado. Paradójicamente (o mejor dicho, *por esa misma razón*) las leyes y regulaciones **lo limitan cada vez más**, alejándolo [con plazos más extensos](/blog/2009/11/veinte-anos-robados-al-pueblo.html) y con [capas insólitas de "derechos"](/blog/2009/07/museos-quemando-cuadros.html):

<q>La existencia de un dominio público rico y diverso es indispensable para la diversidad cultural y la libertad de expresión. La actual disponibilidad de tecnologías que permiten digitalizar obras en dominio público y ponerlas al alcance de la ciudadanía a través de sitios web especializados como Wikimedia Commons o los mismos sitios web de los museos y archivos que los custodian inaugura una serie de oportunidades nunca antes posible, pero pone sobre la mesa una larga serie de nuevos cuestionamientos que requieren análisis y debate.</q> <small>(Bea en ["Digitalización del Dominio Público. Regulaciones y propuestas en relación al dominio público digital"](http://www.bea.org.ar/2011/10/digitalizacion-del-dominio-publico/))</small>.

Cuando Lawrence Lessig propuso, a comienzos de este nuevo milenio, un sistema de renovación y registro obligatorio de copyright en Estados Unidos, **al precio simbólico de un dólar** --conocida como la "Ley Eldred"-- para solucionar el problema de las "obras huerfanas" (quiza el 99% de las obras), recibió una oposición frontal por parte de la industria que lo sorprendió ¿Por qué? ¿acaso no eran obras sin posibilidad de explotación comercial, que ya no le interesaban a nadie? la motivación profunda de la industria era aún más extremista que lo imaginado:

<q>El esfuerzo para bloquear la Ley de Eldred es un esfuerzo para asegurar que el dominio público nunca será competencia, que no habrá ningún uso de contenidos que no esté comercialmente controlado, y que no habrá ningún uso comercial de contenidos que no exija su permiso primero.</q> <small>(Lawrence Lessig en "Cultura Libre", [Capítulo 14](http://www.saber.es/web/biblioteca/libros/cultura-libre/html/t19.htm))</small>.

En efecto, no queda más remedio que recorrer Internet o la Wikipedia para redescubrir a la mayoría de los autores que entran a dominio público cada año, aunque hayan sido ampliamente reconocidos en su época. Luego de períodos de tiempo tan ridículamente extensos, apenas si quedan vestigios del tejido de citas culturales que lleguen hasta el presente. Sin duda, la industria se asegura que todo aquello que no esté fuera del circuito comercial, **no circule, y no sea nunca competencia**: para cuando se liberen sus derechos, ya serán olvido.

Aqui nuestro humilde esfuerzo para tratar de evitarlo.


* * * * *

<span class="float">![image](/media/img/2012/pdd-2012-index.png)</span>
\(1) **El Lissitzky**: Si Usted es un humano "no-diseñador", no habrá oido hablar mucho de Lazar Markovich Lissitzky, o simplemente El Lissitzky, una de las figuras más influyentes en arte y diseño, provenientes del [constructivismo ruso](http://paris.blog.lemonde.fr/2007/07/01/rodchenko-stepanova-paul-schuitema-georgi-et-vladimar-stenberg-el-lissitzky/). Cuando todo estaba por reinventarse en los tiempos heroicos de los soviets, Lissitzky adhirió plenamente a la corriente [suprematista](http://www.google.com/search?q=suprematism+malevich&hl=en&prmd=imvns&tbm=isch&tbo=u&source=univ&sa=X&ei=3FIBT4OcFI-utwe4meTPBg&ved=0CCwQsAQ&biw=1280&bih=830) del pintor y teórico Kazimir Malévich, que colocaba a la vanguardia del arte, al servicio de la vanguardia de la revolución. Es el autor de ["Golpead a los blancos con la cuña roja"](http://www.google.com/search?tbm=isch&hl=en&source=hp&biw=1280&bih=830&q=Beat+the+Whites+with+the+Red+Wedge&gbv=2&oq=Beat+the+Whites+with+the+Red+Wedge&aq=f&aqi=g1g-m2g-S3&aql=&gs_sm=e) una de las obras más emblemáticas del primer período de la revolución. Lissitzky enseñó en el [Vkhutemas](http://en.wikipedia.org/wiki/Vkhutemas) —la escuela rusa de diseño, hermana menos conocida de la célebre [Bauhaus](http://en.wikipedia.org/wiki/Bauhaus)—, y fue una figura influyente de la mencionada escuela de diseño alemana y del movimiento [De Stijl](http://en.wikipedia.org/wiki/De_Stijl) holandés. Por las extrañas vueltas de la remezcla y la reapropiación de estéticas, las formas características del constructivismo ruso [empezaron a verse nuevamente en marcas, logotipos, tipografías y folletos publicitarios de los 80](http://www.barneybubbles.com/blog/archives/1146), bajo la influencia del punk y del diseñador inglés Neville Brody, pertinaz plagiador a conciencia de muchas obras constructvistas. Claro que a diferencia de los frívolos '80, la idea del diseño como herramienta para el cambio social, había quedado algo pasada de moda. Lissitzky murió de tuberculosis en Moscú, en 1941, continuando con su trabajo experimental, a pesar de Stalin y del realismo socialista.

{%- endmark %}

\(2) **Marina Tsvetaeva**: En agosto de 1941, en un lejano pueblo tártaro donde había sido deportada, —[según cuenta Vila-Matas](http://www.letraslibres.com/revista/letrillas/la-galaxia-tsvietaieva)— Marina <q>se ahorcó, dicen que con la cuerda que había utilizado para su maleta del exilio. «Cómo no ahorcarse —diría años más tarde [la escritora rusa] Berberova— cuando la adorada Alemania bombardea tu querido Moscú, los viejos amigos, asustados, se apartan de ti, los periódicos te acusan y no hay nada que comer»</q>. Marina Ivanovna Tsvetaeva fue una poetisa nacida en Moscú, hija de una familia culta y aristocrática, que a pesar de padecer una vida signada por el exilio y la tragedia, dejó una obra actualmente considerada como una de las más importantes de la literatura rusa del siglo pasado, en un estilo difícil de encasillar. Para Marina **la revolución fue un hecho trágico que marcó toda su existencia**. Una de sus hijas murió de hambre en un asilo gubernamental en 1920. Poco después abandonó la Unión Soviética junto con su otra hija y se reencontró con su esposo Serguéi en Praga. Finalmente se instaló en París donde vivio 14 años. El exilio, no la trató mucho mejor que su propio país y la sombra del hambre y la carencia la persiguió por toda Europa. De vuelta en la Unión Soviética escapando de la Segunda Guerra al finalizar la década del 30, su marido Serguéi fue fusilado por sospecha de espionaje, Marina se suicidó, y su hija Ariadna fue reabilitada recién en 1955. Selma Ancira, literata especializada en escritores eslavos, tradujo gran parte de su obra y contribuyó en gran medida a [redescubrir a esta poetisa entre los lectores de habla hispana](http://barriodepalermo.blogspot.com/2011/11/gratis-biblioteca-nacional-homenaje-la.html). La traductora vive y tiene 54 años, con un poco de suerte, quizá no haya que esperar al próximo siglo para festejar el ingreso al dominio público de su obra traducida al español.

\(3) **Lord Robert Stephenson Smith Baden-Powell**, "Primer Barón de Gilwell", fue actor, pintor, músico, militar, escultor, escritor británico, y **fundador del Movimiento Scout Mundial**. [Según dice wikipedia](http://es.wikipedia.org/wiki/Robert_Baden-Powell) <q>participó en distintas campañas militares en África, en las cuales destacó y obtuvo gran popularidad entre la población británica, especialmente por su heroica dirección en la defensa de Mafeking</q>, y luego <q>como héroe de adultos y jóvenes que había regresado de África a Inglaterra, se encontró con la sorpresa que su popularidad personal se había extendido gracias a su libro Aids to Scouting (Ayudas para el Escultismo), destinado al ejército, y que estaba siendo usado como libro de texto en las escuelas para jóvenes</q>. En sus ultimos años Baden-Powell regresó a Kenia junto con su esposa, donde murió a la edad de 83 años, dejando decenas de libros dedicados al *scouting*.

\(4) [**Jelly Roll Morton**](http://www.redhotjazz.com/jellyroll.html), nombre artístico de Ferdinand Joseph LaMothe, alguna vez se definió a si mismo como *"el inventor del jazz"*. Si bien muchos músicos y críticos del género que siguieron no piensan igual, lo cierto es que [*"Jelly Roll Blues"*](http://www.youtube.com/watch?v=Zt203us6TME) es la primer composición de Jazz registrada (en 1915) y es de su autoría. Famoso tanto por su arrogancia, como por su talento, —y por su sobrenombre "el bebedor de vino"— Jelly Roll Morton nació en New Orleans, Louisiana. A los 14 años comenzó a trabajar tocando el piano en un burdel y eso le valió el rechazo de su familia. Comenzó a vagar por el sur de Estados Unidos, junto con espectáculos de vodevil, y a escribir su leyenda: compuso durante esa vida errante muchos temas que hoy son estándares del jazz y del blues, ["Wolverine Blues"](http://www.youtube.com/watch?v=s5XOjIhTMK4), ["Black Bottom Stomp"](http://www.youtube.com/watch?v=xGAeqQNh3cI), o ["King Porter Stomp"](http://www.youtube.com/watch?v=h8_2ISGOIjU). En la década del 20, *"Jelly Roll Morton’s Red Hot Peppers"* grabaron en Chicago para la RCA Victor varios de los registros clásicos del Jazz de sus inicios. Luego su carrera comenzó a declinar. Probablemente no haya género musical más hostil a la idea de "invención individual" que el Jazz, sin embargo es indudable que LaMothe fue uno de sus precursores más importantes. Por suerte no se le ocurrió ponerle patente a su invento.

\(5) [**Robert Delaunay**](http://en.wikipedia.org/wiki/Robert_Delaunay) fue un pintor francés, cofundador del movimiento pictórico conocido como "orfismo", caracterizado por la abstracción, los colores fuertes y las formas geométricas. Iniciado en el cubismo, son muy conocidas sus [estudios con la imagen de la Torre Eiffel](http://www.google.com/search?q=Delaunay+eiffel&hl=en&prmd=imvns&tbm=isch&tbo=u&source=univ&sa=X). En 1912 abandonó por completo la figuración, para unirse junto con su esposa Sonia —también pintora— a un grupo de pintores de París que experimentaban con la abstracción, iniciando el movimiento de "cubismo órfico". Esta denominación fue acuñada por Apollinaire, que se refería al orfismo como <q>el arte de pintar conjuntos nuevos con elementos no tomados de la realidad visual, sino totalmente creados por el artista y dotados por él de una poderosa realidad. Es arte puro</q>. La fiebre de la vanguardia o la reacción a la figuración, quizá hizo olvidar a Apollinaire que la pintura no es más que un diálogo con la misma pintura, no con la realidad, donde las palabras ya han sido inventadas hace tiempo, colectivamente. Sólo se reciclan.

\(6) **Sir Rabindranath Tagore** fue un poeta bengalí, nacido en Calcuta, también filósofo, músico, pintor y dramaturgo. Fue distinguido con el **Premio Nobel de Literatura en 1913**, convirtiéndose así en **el primer no europeo en obtener este reconocimiento**. Hijo de un *maharishi* y de una familia pudiente, Rabindranath estudió en Inglaterra, y con el tiempo se convirtió en gurú, filosofo, pensador, religioso, liderando una comunidad autosuficiente establecida en la región de [Bengala](http://es.wikipedia.org/wiki/Bengala) (La India), frecuentemente visitada por estudiantes, artistas, e intelectuales occidentales. Su fama lo llevó a recorrer el mundo. Sus funerales, en 1941, fueron un suceso conmocionante y masivo en La India. En The Guardian se preguntaban hace poco [¿quien lee hoy a Tagore?](http://www.guardian.co.uk/commentisfree/2011/may/07/rabindranath-tagore-why-was-he-neglected), dando cuenta de las pocas traducciones y poca difusión que este autor recibe en el presente, fuera de su país. La anécdota telúrica: una de sus giras lo dejó varado en Argentina, en 1924. Aquejado por una enfermedad, [pasó dos meses como huésped de Victoria Ocampo](http://www.lanacion.com.ar/1431786-recuerdan-la-amistad-de-tagore-y-victoria-ocampo) en una quinta en San Isidro. El bengalí le dedicó más de un poema de amor y su relación perduró a través de los años. El le dedicó libros, ella le organizó exposiciones. [Hasta hay un película en camino](http://masquevidadigital.blogspot.com/2011/12/la-pelicula-argentina-sobre-tagore-y.html). Es sabido que cuando las obras entran en dominio público florecen las traducciones y reediciones al liberarse el monopolio. Aunque relegado por los plazos infinitos de las leyes actuales, el dominio público parece llegar algo tarde para Tagore. Por suerte, todavía llega.

\(7) **James Joyce**, sin duda no necesita reseña, para muchos escribió el libro más grande del siglo pasado, el *Ulysses*. No nos vamos a perder esta cita remanida del propio Joyce sobre su libro: <q>he planteado tantos enigmas y quebraderos de cabeza [en Ulises] que tendré ocupados por siglos a los profesores, que discurrirán sobre todo lo que he querido decir</q>. Y lo logró. La historia de Joyce, del [Ulises](http://www.jstor.org/pss/797499), del [Bloomsday](http://www.lapetiteclaudine.com/archives/005056.html) y hasta la de [su nieto](http://www.bea.org.ar/2006/06/16-de-junio-bloomsday/) —en relación a los temas que tratamos en Derecho a Leer— es tan jugosa que esta reseña no alcanza ni como introducción. Digamos que nació en Dublín, que escribió sobre Dublín, que se "autoexilió" en Italia, Suiza y Francia, que no era abstemio y que el mismísimo Karl Jung, que tuvo como paciente a su hija esquizófrenica, le diagnosticó la misma enfermedad al padre luego de leer Ulises: afirmó que ambos, padre e hija, <q>se deslizaban al fondo de un río, sólo que él sabía bucear y ella se hundía irremediablemente</q>.

\(8) **Virginia Woolf**, junto con Joyce y Proust es una de las figuras centrales de la narrativa modernista. [Ya le dimos a bienvenida con anticipación](/blog/2011/12/bienvenidos-al-dominio-publico-virginia-woolf.html). Como nota de color, hay que decir que **no es la primera vez que Virginia Woolf ingresa al dominio público**, [ya lo hizo](http://www.elpais.com/articulo/cultura/WOOLF/_VIRGINIA/JOYCE/_JAMES/Feroz/batalla/editorial/pasar/dominio/publico/derechos/Joyce/Virginia/Woolf/elpepicul/19920106elpepicul_2/Tes) —junto con Joyce— hace 20 años, cuando la extensión el copyright en Europa era de 50 años *post-mortem*. Las editoriales, hicieron todos los preparativos para lanzar sus propias ediciones en el 92. Sin embargo, la década del 90 fue un hito en reformas sobre las legislaciones de derecho de autor, tanto de Europa como Estados Unidos, y se extendieron los plazos por 20 años **devolviendo a ambos autores al dominio privado** poco después de su entrada al patrimonio universal (se supone que esto es algo legalmente escandaloso, pero los *lobbies* todo lo pueden). Robert Spoo un académico estadounidense especializado en copyright afirma que la evidencia sugiere que el dominio público **ha tenido un impacto especialmente benéfico sobre las obras del modernismo en Estados Unidos** (que no son precisamente *best-sellers*), *"A Portrait of the Artist as a Young Man"* de Joyce entró *definitivamente* en dominio píblico en 1992 (por laberintos legales largos de explicar). Como consecuencia ha tenido infinidad de ediciones críticas de calidad, y de bajo costo, a diferencia de las obras que siguen en dominio privado. Esperemos que este actual ingreso al dominio público, tanto de Woolf como de Joyce, sea el definitivo...

\(9) [**Henri-Louis Bergson**](http://en.wikipedia.org/wiki/Henri_Bergson) fue Premio Nobel de Literatura en 1927, y uno de los filósofos franceses mas importantes de su tiempo. Su filosofía es una reacción al **positivismo y al racionalismo dominantes**, y lógicamente rescata la experiencia, la intuición y el enfoque vitalista para estructurar su pensamiento. Como una historia que se repite, los (estériles) debates entre los "científicos duros" y los "humanistas blandos" seguirán estando en el candelero intelectual. Y la obsesión de los primeros por la aplicación metafórica que hacen los segundos de sus teorías, seguirá siendo un clásico bizantino. [Hace poco fue Sokal](http://es.wikipedia.org/wiki/Escándalo_Sokal), pero en 1911 fue el libro de Bergson ["Duración y Simultaneidad" y nada menos que el físico Albert Einstein y la relatividad, el concepto en disputa](http://www.fas.harvard.edu/~hsdept/bios/docs/canales_vision_del_infinito_2.pdf). La filosofía de Bergson llegó a convertirse en moda intelectual e influyó sobre varios pensadores y artistas en la primera mitad del siglo XX. Setenta años después de su muerte la obra del "filósofo de la intuición" acaso se encuentre algo relegada. Sin embargo, nada como los laberintos de dimensiones invisibles, materia oscura, mundos paralelos e intuición radical de la dura física teórica del presente, como para reivindicar a los irracionalistas de todas las épocas, incluído Bergson, de un plumazo.

