---
title: 'Resumen de noticias de diciembre'
author: derechoaleer
created: !!timestamp 2012-01-14 04:13:43
tags: 
    - Brasil
    - p2p
    - Leyes
    - Libertad de expresión
    - Derechos retrográficos

comments: 2
nid: 428
order: 360
type: story
status: 1
format: 2
---

{% mark excerpt -%}
*Varias noticias copyfight de diciembre (sin sopa, eso sí), desde Suiza, Holanda, la Unión Europea, Brasil, Canadá, que dieron vuelta la blogófera y se nos quedaron en el tintero...*
### Unión Europea: prohibido filtrar

<span class="float">![image](/media/img/2012/ue-map.jpg)</span>A finales de noviembre se produjo un **fallo ejemplar del Tribunal de Justicia Europeo**: [El fin no justifica los medios](http://www.bea.org.ar/2011/11/fallo-ejemplar-del-tribunal-de-justicia-europeo/). En el caso de **Scarlet vs. SABAM** (la proveedora de conexión a internet y la gestora colectiva, ambas de Bélgica), había una condena en primera instancia que obligaba a la teleoperadora a la instalación de un **sistema de filtrado** para detectar y neutralizar "violaciones del copyright" a través de programas P2P. [Según informa Publico.es](http://www.publico.es/culturas/408740/la-ue-prohibe-a-los-operadores-vigilar-a-los-usuarios-de-p2p) el fallo dictamina que <q>ningún Gobierno de la Unión Europea puede obligar a una compañía que suministre conexión a Internet a que vigile qué comparten sus clientes en redes de intercambio peer to peer</q>. El tribunal recordó que <q>las reglas comunitarias establecen «la prohibición» de luchar contra las violaciones de derechos de autor a través de «medidas que obliguen a un proveedor de acceso a Internet a proceder a una supervisión general de los datos que transmita en su red»</q>.

### ACTA pasa el Consejo Europeo

Mezclados en un mismo paquete con regulaciones pesqueras (!), el Consejo de la Unión Europea (algo así como una institución intermedia entre la Comisión Europea, y el Parlamento Europeo) dió luz verde al [ACTA](/blog/2011/09/infografia-acta-un-arma-de-destruccion-masiva-contra-tus-derechos.html), el tratado internacional que pretende establecer un [duro estándar represivo en lo relativo a propiedad intelectual](https://www.laquadrature.net/en/infographic-remix-acta-lethal-weapon-against-your-rights) (desde medicamentos, hasta intercambio de archivos). <q>ACTA se pasó debajo de una pila de documentos relacionados con flotas pesqueras, pesca y comercio agropecuario</q>, [observa Geraldine Juárez en ALT1040](http://alt1040.com/2011/12/el-consejo-de-la-union-europea-adopta-acta), <q>Cualquier similitud entre las leyes de propiedad intelectual y el pescado, no es coincidencia. Ambos apestan cuando salen a la superficie</q>... Habrá que ver ahora qué dice el parlamento.

### Suiza, sí al P2P

<span class="float">![image](/media/img/2012/suiza-map.jpg)</span>A principios de diciembre, sorprendió una noticia proveniente de Suiza: [las descargas e intercambio de música y películas por internet debe seguir siendo legales, en ese país](http://torrentfreak.com/swiss-govt-downloading-movies-and-music-will-stay-legal-111202/) —y no deberían aprobarse leyes que intenten reprimir esta práctica. Según [un estudio](http://translate.google.com/translate?hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=de&tl=es&twu=1&u=http://www.ejpd.admin.ch/content/dam/data/pressemitteilung/2011/2011-11-30/ber-br-d.pdf) encargado por el Consejo de los Estados (la Cámara Alta de Suiza), concluye que **el intercambio en internet no provoca pérdidas a la industria** (comprueba con datos que no ha disminuído el dinero que el público destina a gastar en entretenimiento, incluso en el segmento que más descarga), que **es la industria la que debe adapatarse a las nuevos medios y no a la inversa**, y que poner en práctica medidas en contra de este "problema" (que implícitamente admite como inexistente) **afecta los derechos ciudadanos, la privacidad y el acceso a la cultura y el conocimiento**, además de requerir una infraestructura legal y técnica bastante costosa, y [probadamente ineficiente](http://www.20minutos.es/noticia/648371/0/descargas/p2p/francia/).



{%- endmark %}

{# break #} Para Clarin sin embargo, [es un estudio "polémico"](http://www.clarin.com/internet/polemico-estudio-suizo-descargas-ilegales_0_608339246.html). Para cualquier usuario de internet, rebosa de sentido común. Suiza es uno de los países que [negocian el ACTA](/blog/2011/09/infografia-acta-un-arma-de-destruccion-masiva-contra-tus-derechos.html), pero que aún no lo firmó. Otro antecente: en 2010 Suiza [declaró ilegal la actividad de las empresas que monitorean las redes P2P en busca de infractores al copyright](http://torrentfreak.com/anti-piracy-monitors-banned-from-operating-in-home-country-100909/).
### Holanda, sí al P2P

<span class="float">![image](/media/img/2012/holanda-map.jpg)</span>En Holanda, tras meses de debate [el parlamento decidió mantener legales las descargas en internet](http://www.enriquedans.com/2011/12/las-descargas-de-musica-y-peliculas-seguiran-siendo-legales-en-holanda.html). Basándose en un estudio comisionado en 2009 [llegó a la misma conclusión](http://es.scribd.com/doc/76424564/Ups-and-Down-Author-is-Ed-Translation-Final) que el suizo: [restringir el libre flujo de información por la red invade la privacidad de los ciudadanos](http://torrentfreak.com/dutch-parliament-downloading-movies-and-music-will-stay-legal-111224/). Al igual que en Suiza, se comprobó que **un tercio de los holandeses decarga e intercambia música y películas como práctica corriente** ([los internautas estadounidenses también](http://mark.goodge.co.uk/2012/01/study-finds-that-filesharing-is-about-convenience/)). Un estudio encargado por el gobierno inglés en 2011, el informe [Hargreaves](http://en.wikipedia.org/wiki/Hargreaves_Review_of_Intellectual_Property_and_Growth) resumió: [necesitamos *evidencias*, no propaganda](http://www.quemarlasnaves.net/informe-hargreaves-evidencia-contra-la-intuicion/).

### Epic Fail I: la anti-piratería no paga

Fundamentar en un absurdo una postura, es el camino inexorable hacia el rídiculo, por ejemplo sostener que la práctica de compartir por internet debe considerarse como un crimen repudiable. La evidente contradicción, a la larga termina expuesta. Si todos lo hacen, y no hay sanción social, menos puede haber sanción legal. Siguiendo la tradición del ["powerpoint pirata" del anti-pirata Fernando Ubiergo](http://www.fayerwayer.com/2009/01/el-powerpoint-pirata-de-fernando-ubiergo/), o el [logotipo pirata de la anti-pirata Hadopi](http://www.fayerwayer.com/2010/01/el-logotipo-de-hadopi-infringe-derechos-de-autor/), esta vez **le tocó a la gestora colectiva holandesa** (Buma/Stemra) . [El papelón](http://torrentfreak.com/copyright-corruption-scandal-surrounds-anti-piracy-campaign-111201/?_) comienza por ["el olvido" del pago de los *royalties*](http://www.nacionred.com/lobbies-pi/un-lobby-antidescargas-utiliza-una-cancion-de-un-musico-sin-su-permiso-para-un-anuncio-antipirateria) al músico encargado de componer nada menos ¡que la música del clásico anti-piratería ["no robarías un auto..."](http://www.youtube.com/watch?v=K_vHwfDNGdg)! para luego, ante el reclamo del autor, concluir con **un pedido de coima al artista por parte uno de los directivos de la gestora** "para agilizar el pago". Papelón al cuadrado, una cosa es cobrar derechos, otra pagarlos.

### Epic Fail II: Cazadores Cazados

<span class="float">![image](/media/img/2012/rusia-map.jpg)</span>[YouHaveDownloaded.com](http://youhavedownloaded.com) es una página rusa dedicada a revelar las direcciones IP de aquellos que han intercambiado archivos en redes [BitTorrent](http://es.wikipedia.org/wiki/BitTorrent) —al menos del 20% de los [trackers](http://es.wikipedia.org/wiki/Tracker_(BitTorrent)) públicos. El objetivo de la página es concientizar acerca de la escasa protección que la red torrent otorga a sus usuarios **para mantenerlos anómimos**, al contrario de la creencia corriente. YouHaveDownloaded.com devuelve **una lista de todos los archivos que se han descargado desde el IP solicitado**. Pero el servicio **produjo un efecto no previsto**: algunos suspicaces usuarios comenzaron a preguntarle al sitio por las direcciones IP de gobiernos, gestoras de derechos, políticos, discográficas o estudios de cine.

![image](/media/img/2012/sony-bust.jpg)<span class="epigrafe">Las direcciones IP de Sony desde donde se realizaron descargas que la misma Sony considera ilegales. y por las que frecuentemente realiza demandas judiciales.</span>

Fue así que direcciones IP de [Sony Pictures, Universal, Fox](http://torrentfreak.com/busted-bittorrent-pirates-at-sony-universal-and-fox-111213/), [la residencia del Presidente Sarkozy](http://torrentfreak.com/french-presidents-residence-busted-for-bittorrent-piracy-111215/) (el impulsor de Hadopi), el [Departamento de Seguridad Nacional de los Estados Unidos](http://tecnocapsulas.com/2011/12/20/riia-y-seguridad-nacional-atrapados-descargando-torrentes/), [la gestora de derechos holandesa Buma/Stemra](http://www.geenstijl.nl/mt/archieven/2011/12/onthullend_dit_downloadt_neder.html) o la mismísima RIAA, figuraron descargando películas, software o música según sus propios términos, "ilegalmente". La gestora holandesa fue [la primera en contestar](http://www.bumastemra.nl/nieuws-artikel/reactie-bumastemra-op-berichtgeving-geen-stijl-over-downloaden/). **Es una respuesta difícil**, o se reconoce la falta, colocándose en flagrante contradicción, o se excusa fundando su inocencia en el **uso no autorizado de sus direcciones IP**, en cualquier caso **es un jaque mate**: también los usuarios perseguidos por esas mismas organizaciones, podrán alegar desconocimiento sobre el uso de su propia IP. Buma/Stemra contestó lo primero en un parte de prensa, aunque luego lo borró de su sitio. En españa, [la SGAE, La Moncloa y el ministerio de cultura](http://www.fayerwayer.com/2011/12/espana-en-el-ministerio-de-cultura-la-sgae-y-moncloa-tambien-usan-bittorrent/) (los promotores de la Ley Sinde) también fueron cazadores cazados.

### Debates en Brasil

<span class="float">![image](/media/img/2012/brasil-map.jpg)</span>En Brasil sigue el debate por las modificaciones a la ley de derecho de autor. Durante la presidencia de Lula, primero con el ministro Gilberto Gil, y luego con su sucesor, Juca Ferreira, se inició [un alentador proceso de reforma](/blog/2010/12/brasil-por-el-buen-camino.html). Pero con el relevo presidencial, la nueva ministra Ana de Hollanda [marcó un cambio de rumbo con su gestión](/blog/2011/01/la-mujer-que-se-robo-todas-las-miradas-asuncion-dilma.html): como primera medida eliminó las licencias Creative Commons que el mismo Ministerio de Cultura utilizaba en su sitio, dijo al respecto: [<q>es hacer propaganda a una entidad privada que ofrece un servicio</q> (sic)](http://oglobo.globo.com/cultura/em-audiencia-no-senado-ministra-ana-de-hollanda-nega-relacao-com-ecad-confunde-natureza-do-creative-commons-2799612), y anunció que revisaría lo hecho hasta entonces.

Sin embargo en diciembre de 2011 la Ministra anunció que ya estaba listo el texto con la revisión del proyecto de ley y que era ["un 85%" igual a la propuesta de la gestión anterior](http://oglobo.globo.com/cultura/ana-de-hollanda-segue-juca-ferreira-nos-direitos-autorais-3323719). La ministra [enfrenta duras resistencias en el propio PT, por razones varias](http://www.estadao.com.br/noticias/nacional,retrospectiva-2011-ana-de-hollanda-enfrenta-polemica-frente-ao-ministerio-da-cultura,812656,0.htm), y probablemente haya disminuído su margen de acción para enfrentar a los sectores que defienden lo hecho durante la gestión de Juca Ferreira y Gilberto Gil. La ley incluye algunos puntos positivos, en especial si tomamos en cuenta el presente desalentador de ACTAs y SOPAs, por ejemplo: **incorporación de excepciones para bibliotecas, excepciones educativas o copia privada (sin canon!)**. [En *O Globo* hicieron una infografía](http://oglobo.globo.com/infograficos/direito-autoral/).

![image](/media/img/2012/hollanda-ortellado-affonso.jpg)<span class="epigrafe">Ana de Hollanda, Ministra de Cultura de Brasil, y los especialistas en propiedad intelectual, acceso y nuevas tecnologías, Pablo Ortellado (GPOPAI) y Carlos Affonso (FGV).</span>

La polémica comenzó cuando se supo que entre "el 15%" de diferencias, se habia colado un artículo sobre [*notice and take down*](http://en.wikipedia.org/wiki/Online_Copyright_Infringement_Liability_Limitation_Act#Takedown_example) en el proyecto (procedimiento que propicia un virtual estado de censura en internet: los proveedores de servicio, para no ser responsables ante los denunciantes, terminan dando de baja contenidos ante la primer denuncia, convirtiendose en un árbitro de facto que reemplaza a la justicia, y esto [según la opinión de un documento de la ONU](http://www.bea.org.ar/2011/11/sobre-el-bloqueo-a-cuevana/)). [Las críticas no se hicieron esperar](http://autoriaemrede.wordpress.com/2011/12/09/retrocesso-na-revisao-da-lei-de-direito-autoral/). [**Pablo Ortellado**](/blog/2010/07/copyright-y-acceso-al-conocimien.html) de GPOPAI (Universidad de Sao Paulo) afirmó que <q>‘Notice and take down’ es censura previa</q>, <q>De igual forma si el usuario [que subió el contenido] se responsabiliza, la obra es dada de baja por el sitio. El proveedor da de baja, para evitar un proceso legal. Y las gestoras muchas veces no disponen de los derechos</q> mantener un blog de MP3, para Ortellado, <q>va a ser imposible</q>. Inmediatamente el ministerio [salió a contestarle](http://www.cultura.gov.br/site/2011/12/05/nota-de-esclarecimento-33/) sosteniendo que la medida no implicaba censura. Ortellado, en una fundamentada respuesta en su blog, [sostuvo su postura](http://www.gpopai.org/ortellado/2011/12/resposta-ao-minc-sobre-o-mecanismo-de-notificacao-e-retirada/). En sintonía con Ortellado, **Carlos Affonso** (Coordinador del Centro de Tecnología y Sociedad de la Fundación Getúlio Vargas), en una entrevista, coincidió sobre [el retroceso que significaría](http://terramagazine.terra.com.br/interna/0,,OI5494774-EI6578,00-Nova+Lei+de+Direito+Autoral+pode+ter+efeitos+nocivos+a+internet+diz+professor.html) dar estatus legal al *take-down* en la futura Ley. El debate sigue abierto.

### Debates en Canadá

<span class="float">![image](/media/img/2012/canada-map.jpg)</span>Mientras Canadá recibe presiones para [extender sus "modestos" 50 años *post-mortem* de copyright a 70](http://www.michaelgeist.ca/content/view/6225/125/), en medio de negociaciones para ingresar al [Tratado de Libre Comercio Traspacífico](http://en.wikipedia.org/wiki/Trans-Pacific_Strategic_Economic_Partnership) (cuándo no!), los [**músicos y autores canadienses se pronuncian a favor del P2P**](http://www.nacionred.com/legislacion-pi/autores-canadienses-a-favor-de-legalizar-el-intercambio-p2p): <q>Todos hemos compartido música y siempre lo haremos. La música que compartimos define quienes somos, y quienes son nuestros amigos y compañeros. La importancia de la música en el tejido de nuestra cultura, y también por el resto del mundo, está intrínsecamente ligada a la experiencia de compartir</q>, tambien creen que **Internet ha reavivado el negocio musical**, que **no todo lo que hacen las discográficas es en interés de músicos y artistas** y que **el público debería tener acceso a toda la música del mundo**. Lo dijo Jean-Robert Bisaillon, presidente de la Asociación de Autores de Canadá (Songwriters Association of Canada).





