---
title: 'El telégrafo ataca de nuevo (I)'
author: derechoaleer
created: !!timestamp 2012-12-09 10:10:34
tags: 
    - Dependencia tecnológica
    - Imperialismo y monopolios intangibles
    - Internet
    - Medios
    - Redes distribuidas
    - Reflexión

type: story
status: 1
comments_status: open
---

{% mark excerpt -%}

<div class="intro" markdown="1">
En estos días se celebra en Dubai la [**WCIT**](http://www.vialibre.org.ar/2012/12/05/wcit-los-riesgos-de-controlar-internet/) (Conferencia Internacional de Telecomunicaciones) organizada por la ITU (Unión Internacional de Telecomunicaciones) --que tiene por objeto la actualización de las regulaciones internacionales de telecomunicaciones, cuyo último acuerdo data de... [¡1988!](http://www.itu.int/es/wcit-12/Pages/itrs.aspx)-- que para temor de muchos, incluye dentro de su agenda la posibilidad de acordar [**normativas para la regulación de internet**](http://www.youtube.com/watch?v=XzNQarkk95Q). Desde [Google](https://www.google.com/intl/es/takeaction/) y [Mozilla](https://webmaker.org/en-US/ITU/kit/) hasta el [Parlamento Europeo](http://www.queeslauit.org/documentos/resolucion-del-parlamento-europeo-sobre-cmitwcit/) han expresado su preocupación. La [ITU](http://www.queeslauit.org/) es un organismo de regulación [obsoleto para muchos](http://www.lanacion.com.ar/1534668-el-sueno-obsoleto-de-una-internet-bajo-control), poco transparente y de participación muy limitada, para definir algo tan sensible como los estándares de internet. Honestamente, el tema regulatorio es algo tedioso, pero desde derechoaleer aprovechamos para preguntamos ¿qué es la ITU? ¿cuál es su historia? ¿qué tiene que ver el telégrafo con internet? ¿cómo era "la madre de todas las redes"? anduvimos indagando un poco, y encontramos algunas cosas curiosas, como para publicar algunos artículos, aca va el primero...
</div>

![El telégrafo ataca de nuevo](/media/img/2012/itu/telegrafo-640.jpg)

### La Madre de Todas las Redes

> <q>En el siglo XIX no había televisión, aviones, computadoras o naves espaciales, tampoco había antibióticos, tarjetas de crédito, hornos a microondas, discos compactos o teléfonos móviles. Sin embargo, si había internet.</q>

> <q>Durante el reinado de la Reina Victoria, fue desarrollada una nueva tecnologia de comunicaciones que le permitió a la gente comunicarse instantaneamente a través de grandes distancias. En efecto, el mundo se achicó como nunca antes. Una red mundial de comunicaciones que extendió sus cables a través de océanos y continentes, revolucionó la forma de hacer comercio, generó nuevas formas de cometer fraudes y crímenes, e inundó a sus usuarios con un diluvio de información. Floreció el romance a través de los cables. Algunos usuarios diseñaron códigos secretos para proteger sus comunicaciones... que fueron crakeados por otros usuarios. Referirse a los grandes beneficios de la red fue un tópico insistentemente promocionado por sus defensores, y desestimado por los escépticos. Gobiernos y regulaciones pretendieron --y fallaron-- en su intento de controlar el nuevo medio. Desde la diplomacia hasta la distribución de noticias tuvieron que pensarse nuevamente. Y mientras tanto, en medio de los cables, una subcultura tecnológica con sus propios códigos y vocabularios, emergió por su cuenta.</q>

> <q>Esto ¿les suena familiar?</q>

Así comienza el libro [*"La Internet Victoriana"*](http://avaxhome.ws/ebooks/history_military/0802713424.html), escrito por Tom Standage y lógicamente no se refiere a la internet que conocemos, sino a otra red que revolucionó al mundo y también utilizaba un código binario, pero de rayas y puntos. La *madre de todas las redes* se llama *red telegráfica*, que Samuel Morse terminó de inventar en 1836, (junto con William Cooke y Charles Wheatstone, aunque cada uno por su lado...). Encerrado "en su garage" y a partir de artículos de su estudio como <q>un caballete, un lápiz, piezas de un reloj viejo y un péndulo</q>, este *"hacker"* y pintor, puso a punto su artefacto e ideó el código para posibilitar la comunicación, código que en realidad desarrolló un tal [Alfred Vail](http://en.wikipedia.org/wiki/Alfred_Vail) --pero si no quieres ser olvidado por la Historia, no olvides [ponerle tu propio nombre a tus cosas](http://www.gnu.org/gnu/why-gnu-linux.html).

De las [muchas variantes desarrolladas durante el s. XIX](http://distantwriting.co.uk/instruments.html), el telégrafo de Morse fue el más extendido y unas décadas después, las líneas telegráficas recorrían todo el globo. Al igual que internet ahora, **prometió concordia, paz mundial y progreso**, y cuando la red llegó al climax de su crecimiento, **explotaron dos guerras mundiales** que costaron la vida a decenas de millones de personas. Algo semejante puede decirse de la [difusión del telégrafo en Estados Unidos y su guerra civil](http://histsociety.blogspot.com.ar/search/label/Telegraph)[^1]. Por otra parte, fue claramente funcional a la hegemonía de los intereses imperiales de aquel entonces. Pero hay más parecidos.

<span class="img">![Chat telegráfico](/media/img/2012/itu/wireless-telegraph.png)<span class="ep">La noticia del "telégrafo inalámbrico" motivó [esta caricatura de 1907](http://classic.tcj.com/history/hats-and-screens/), un notable vaticinio con un siglo de antelación. Muchas formas de interacción que emergieron de internet, no son tan novedosas como suele imaginarse, por ejemplo en los momentos de inactividad de la red telegráfica, los operadores no dejaban de transmitir. Ocurría un fenómeno que ahora resulta familiar, simplemente, comenzaban a charlar entre ellos a la distancia, es decir *"chateaban"* sobre cualquier trivialidad, utilizando el telégrafo.</span></span>



### Piratas cripto-telegráficos

Un aspecto sorprendente de la historia de esta red, es la sofisticada saga *"criptográfica"* que enfrentó a usuarios y compañías telegráficas. En cuanto se permitió el uso público del telégrafo, y en cuanto los gobiernos establecieron las primeras **prohibiciones** sobre que tipo de información podía enviarse por esta vía --el resultado de las carreras de caballos, por ejemplo-- **el valor de la información comenzó a cotizar como nunca antes**: algo que era dominio público en Londres, podía ser valiosa información en Escocia. Como el uso de mensajes cifrados servía para eludir estos controles *al contenido* de los telegramas, entonces, salvo para gobiernos y funcionarios de correo, esta clase de mensajes **quedó terminantemente prohibida**. Pero esta disposición no era difícil de evitar, se podía enviar la información en algún idioma más o menos exótico. ¿Qué medida se tomó entonces? limitar el uso de idiomas que se podían utilizar en un telegrama...

A diferencia del viejo continente, los *"cripto-telegramas"* **sí estaban permitidos en Estados Unidos**, donde las empresas telegráficas eran privadas y había menos interés del gobierno en el tema. Incluso se publicaban libros sobre como codificar mensajes, utilizados principalmente para proteger el secreto comercial. Ciertos métodos de cifrado además de proteger la información, **reducían notablemente la cantidad de caracteres necesarios**. Un telegrama de 90 palabras, podía reducirse a 10. En efecto, **comprimían** la información. Esta optimización, lamentablemente, hacía perder dinero a las compañías telegráficas que cobraban por el largo del mensaje transmitido (o al menos eso creían), además de dificultar el trabajo del operador: muchos telegramas consistían en una larga, única e impronunciable palabra que debía deletrearse... Entonces las compañías privadas también comenzaron a presionar por limitar esta práctica. 

{%- endmark %}


<span class="img-float" style="width:250px;">![Manual criptográfico comercial, para telégrafo](/media/img/2012/itu/cipher_book.jpg)<span class="ep" style="margin-top:0.5em;">[manual para cifrado de mensajes telegráfico](http://www.jmcvey.net/cable/ex/murray_vass_1876.htm). Los usuarios más frecuentes de estos manuales eran los corredores de comercio, en parte para mantener en reserva la información, pero también para *"comprimir"* el mensaje y reducir el costo del envío.</span></span>A medida que la red se extendió, las reglas acerca del uso de códigos de cifrado, lenguajes, o incluso el largo de palabras, se hizo cada vez más sofisticado. Algunos países, por ejemplo, disponían que **una copia de los telegramas debía quedar en poder de la compañía telegráfica por determinado tiempo** (premonitorio ¿no?). 

Finalmente, para poner algo de orden a esta normativa que fue elaborándose algo improvisadamente en cada país, en 1865, los principales países de Europa enviaron delegados a una convención celebrada en París, que dio origen a la **International Telegraph Union**, el primer organismo internacional de la era moderna y objeto de interés de esta serie de artículos. La regulación sobre la criptografía fue un verdadero desafío para la ITU: A la prohibición de utilizar palabras imposibles de pronunciar, llegaron los cifrados con palabras exóticas, largas... pero *fáciles de pronunciar*. Entonces se dispuso que las palabras no debían exceder un determinado número de sílabas. Se generaron códigos con *palabras más cortas*. Luego se dispuso que las palabras debían ser términos que figuraran en el diccionario y del grupo de idiomas autorizados. Los métodos de cifrado pasaron a ser elaborados entonces con *palabras que oficialmente figuraban en los diccionarios* de francés, inglés, alemán y demás  "permitidos". Cada intento de las compañías de evitar el uso de mensajes en clave, no hacia otra cosas que **incentivar el ingenio de los criptógrafos**.

La cosa llegó al climax en 1890 cuando la ITU decidió cortar por lo sano y elaborar un **vocabulario propio de términos telegrafiables**. Publicó una lista de **256.740** palabras, de entre 5 y 10 caracteres, a partir de los ocho lenguajes autorizados. El operador no podía enviar ninguna palabra que no estuviera dentro de esa lista. Lógicamente, la paleta gramatical *se vio severamente empobrecida*. Ante las quejas, la ITU comenzó a elaborar un nuevo vocabulario de **¡un millón de palabras!**. Claro que la necesidad de controlar que las palabras telegrafiadas estuvieran contenidas en tan extensa lista, hacía casi imposible la tarea del operador... Finalmente la ITU aceptó su fracaso y dejo de intentar domesticar a los cripto-rebeldes.

<span class="img">![Chat telegráfico](/media/img/2012/itu/telegraphists_cramp.jpg)<span class="ep">En la actualidad, los ULDs o "Upper Limb Disorders", son afecciones frecuentes originadas tanto en el ámbito laboral, como el privado. Coloquialmente se los conoce como "tendinitis", y la lesión más común es la ["Síndrome del túnel carpiano"](http://es.wikipedia.org/wiki/S%C3%ADndrome_del_t%C3%BAnel_carpiano) que afecta a la muñeca, generalmente provocada por la mala posición del brazo, y a los movimientos repetitivos que requiere el uso del *mouse* o teclado. Pero [nada nuevo bajo el sol](http://diamondenv.wordpress.com/2011/07/27/nothing-new-under-the-sun/), en 1908 el "mal del telegrafista" ya estaba [cubierto](http://books.google.com.ar/books?id=GeWm-zM3NEoC&pg=PA64&lpg=PA64&dq=telegraphist%27s+cramp&source=bl&ots=HgKU6Nqo1S&sig=S3cO9lRT-46SYzhE2snYQz8Nwe4&hl=es-419&sa=X&ei=pCXGUP3oOo6o0AXzg4Bo&ved=0CDEQ6AEwATgK#v=onepage&q&f=false) por la [British Workmen's Compensation Act](http://en.wikipedia.org/wiki/Workmen%27s_Compensation_Act_1897), el movimiento tenso y repetitivo sobre el telégrafo no era diferente del frenético doble-cick.</span></span>


Para terminar esta cripto-historia, vale la pena mencionar otra situación conocida:  a diferencia de lo que ocurría con el correo, muchos usuarios se sentían algo expuestos cuando debían enviar telegramas demasiado personales por una red donde **las palabras eran leídas y releídas por varios operadores** antes de llegar a destino (al igual que los paquetes de internet que circulan a la vista de todos los nodos por donde pasan). La criptografía se hizo particularmente necesaria para proteger... la *privacidad*. Más de un siglo después, uno de [los primeros estándares definidos por la ITU en la WCIT que tiene difusión](http://news.cnet.com/8301-13578_3-57557347-38/u.n-summit-votes-to-support-internet-eavesdropping/), relativos a internet, tiene que ver con una técnica denominada [*"Deep Packed Inspection"*](http://es.wikipedia.org/wiki/Deep_Packet_Inspection), nada menos que la manera de espiar qué llevan los paquetes que pasan por el nodo de algún teleoperador... parece que la criptografía siempre termina siendo nuestro ultimo recurso salvador. 

### El nuevo/viejo ágora universal

Decía Armand Mattelart en una entrevista a Le Monde, <q>Desde la aparición del telégrafo de Chappe, en 1794, tanto los científicos como los políticos han tenido un discurso sobre las promesas emancipadoras de la tecnología a distancia: debe permitir la reconstrucción, a escala de nación, de las condiciones del ágora ateniense</q> El [telégrafo óptico de Chappe](http://es.wikipedia.org/wiki/Tel%C3%A9grafo_%C3%B3ptico), implementado principalmente en Francia, consistía en torres ubicadas a cierta distancia, como semáforos, con un sistema de señales visuales que el operador de cada torre controlaba para transmitir un mensaje. La torre siguiente recibía y volvía a transmitir a la próxima. A pesar del [entusiasmo de algunos intelectuales franceses](http://es.wikipedia.org/wiki/Tel%C3%A9grafo#Utop.C3.ADa_redentora_de_la_comunicaci.C3.B3n_a_distancia) por **las posibilidades que ofrecía el uso civil de esta tecnología**[^3], el gobierno francés **jamás reveló el código** utilizado por el sistema --que sólo era conocido por los funcionarios de cada extremo de la línea. El invento de Chappe no pasó del uso militar y no cumplió la promesa democratizadora. Hubo que esperar a un contexto político [*menos centralizado*](http://lasindias.org/el-poder-de-las-redes/#breve-historia-de-las-redes-sociales)[^4] que el francés, para que el poder aceptara el uso público de semejante invento, la comunicación a distancia instantánea. Llegó con el telégrafo eléctrico, varias décadas después.

<span class="img">![Mapa de los cables telegráficos submarinos](/media/img/2012/itu/740px-1901_Eastern_Telegraph_cables.png)<span class="ep">Mapa de la red de cables submarinos para principios de s. XX.</span></span>

Luego de que [los cables submarinos](http://www.atlantic-cable.com/) se extendieran bajo el atlántico, el pacífico y el índigo, la idea de una infraestructura que posibilitara la "deliberación mundial", parece que finalmente se cumplía. La red revolucionó los medios y el periodismo, con la aparición de las [**agencias de noticias**](http://es.wikipedia.org/wiki/Reuters#Historia) hijas del telégrafo, como *Reuters* o *Associated Press*, que transmitían en *"tiempo real"* cables de información sobre sucesos ocurridos en cualquier lugar del planeta. Pero aquella red también era funcional a un imperio, y los cables se extendían por todo el mundo, pero en algún momento pasaban por un mismo lugar, Londres[^2]. Además, la red fue mayoritariamente explotada por agentes de comercio y funcionarios del gobierno. Al comenzar el siglo XX, según señala wikipedia *"Gran Bretaña ya disponía de un sistema telegráfico de ámbito mundial que conectaba los principales territorios de su imperio"*. Los británicos fueron de lejos, quienes más invirtieron en extender la red, y gran parte de las comunicaciones globales circulaban por líneas de *su propiedad* (incluso la de las potencias enemigas). La red era tan estratégica, que [Inglaterra estatizó por completo](http://en.wikipedia.org/wiki/Telegraph_Act_1868) las empresas de telegrafía y correos para el nuevo siglo.

**Edward Thornton**, el embajador Británico en los Estados Unidos, en ocasión de la primer conexión intercontinental realizada con cable submarino, que unió Irlanda y Terranova, realizó una esperanzadora descripción del suceso: <q>El cable de telégrafo, nervio de la vida internacional, transmitiendo el conocimiento de los hechos, eliminando las causas de los desacuerdos, y promoviendo la paz y la armonía en todo el mundo</q>. Más lejos, había llegado el escritor norteamericano **Nathaniel Hawthorne** en 1851, profetizando que <q>Por medio de la electricidad, el mundo de la materia se ha convertido en un gran nervio, vibrando a miles de kilómetros en un punto de tiempo sin aliento ... El globo redondo es un gran ... cerebro, instinto con inteligencia!</q> 

<span class="img-float" style="width:200px;"><img src="/media/img/2012/itu/algore.jpg" alt="Al Gore" /><span class="ep" style="margin-top: 1em;">Como se parece a Terragno ¿no?</span></span>Casi un siglo y medio después, **otro norteamericano** lo citaba agregando que <q>Por mucho que Jules Verne previó los viajes submarinos y aterrizajes lunares, Hawthorne previó lo que ahora estamos a punto de crear</q>, que son... <q>las autopistas o, más exactamente, redes de inteligencia distribuida --que nos permitirán compartir información, conectarnos y comunicarnos como una comunidad global. A partir de estas conexiones obtendremos un robusto y sostenible progreso económico, democracias fuertes, mejores soluciones a los problemas ambientales globales y locales, mejor atención de salud, y --en última instancia-- un mayor sentido de la corresponsabilidad compartida de nuestro pequeño planeta</q>. Un nuevo/viejo truco siempre eficaz, **vestir de beneficio universal, una agenda de intereses muy concretos**. Ya sea el conflicto de antes, el modelo económico del imperio basado en el librecambio, contra el modelo de sus ex-colonias basado en el proteccionismo, o conflicto actual, el **modelo de control social basado en la abundancia de información, contra los modelos basados en la escasez...** siempre hay agendas ocultas detrás de cada discurso por [más edificante que suene](http://cibermemo.wordpress.com/2012/04/21/1994-un-plan-global-para-la-democracia-y-el-desarrollo/). Las últimas palabras citadas, corresponden al ex-vicepresidente de Estados Unidos **Al Gore**, en un discurso generalmente referenciado como aquel donde [*"Al Gore inventó Internet"*](http://vlib.iue.it/history/internet/algorespeech.html) con motivo de la promoción de la [*National Information Infrastructure*](http://en.wikipedia.org/wiki/National_Information_Infrastructure), pronunciado durante la conferencia plenaria de la **Unión Internacional de Telecomunicaciones, realizada en marzo de 1994 en Buenos Aires**, en plena **euforia de privatizaciones y desregulación menemista de las comunicaciones**. La fibra óptica que quería tender Al Gore, no era muy diferente a los cables de cobre de Edward Thornton, la promesa tampoco.

continuará...

* * * * * 

### Notas

[^1]: <q>Notablemente, los historiadores reconocen que el telégrafo apresuró llegada de la Guerra Civil. Antes de la época de la rápida comunicación, los políticos podían atender a diferentes votantes con promesas contradictorias. Antres de la guerra los demócratas y los liberales podían respaldar la esclavitud en el sur y atacarla en el norte. Siendo que las noticias rara vez llegaban tan lejos, sus discursos difícilmente se volvian en su contra. El telégrafo cambió todo eso. Se ofreció a los votantes una vista más clara en política. Ahora los periodistas podían seguir los políticos y enviar mensajes a los editores de vuelta a casa. Pero una comunicación más rápida no significa necesariamente exactitud. En la otra cara de la moneda, los editores más politizados de medios trataron de situar a sus periodistas en posiciones críticas de tal forma que pudieran dar el enfoque de preferencia a la historia que estaban contando. Se ponian muy felices cuando daban vuelta historias desconcertando a los políticos que se oponían. A medida que la crisis política se acrecentó, el telégrafo permitió editores más comprometidos con algún bando, retratar desde la distancia los acontecimientos de maneras que reforzaron sus propios prejuicios. La cobertura inmediata, quitó a los políticos la capacidad de ignorar el abismo entre el Norte y el Sur. Obligó a los blancos sureños a defender la esclavitud, e hizo norteños sensibles al creciente poder del Sur sobre el gobierno. Los partidos políticos dejaron de tener capacidad para seguir siendo competitivos a nivel nacional, el partidismo se incremento, y la nación se dividió. El resultado fue sangriento.</q> Cox Richarson en [*"The Telegraph and the Information Revolution"*](http://histsociety.blogspot.com.ar/search/label/Telegraph).
[^2]: <q>[...] hoy en día, igual que en el siglo xix en que Londres fue lugar de paso obligado para las redes transcontinentales del sistema mundial de cables submarinos, los Estados Unidos se han convertido en la encrucijada por la que han de transitar necesariamente los internautas de los países menos favorecidos para conectarse entre sí. Los más pobres pagan por los más ricos. Cuando un norteamericano envía un correo electrónico a un africano, el africano es el que paga. Mientras que la tarifa promedio de conexión por veinte horas de un norteamericano o de un finlandés se situaba, en el 2001, en los treinta dólares, superaba ampliamente los cien dólares en los países escasamente conectados.</q> Armand Mattelard ["Historia de la Sociedad de la Información"](http://es.scribd.com/doc/31032411/Mattelart-Armand-Historia-de-la-sociedad-de-la-informacion), pag. 154.
[^3]: <q>«Se ha dicho algo en relación con el telégrafo que me parece infinitamente justo y que pone de manifiesto toda su importancia; es que el fondo de este invento puede bastar para hacer posible el establecimiento de la democracia en un gran pueblo. Muchos hombres respetables, entre los cuales hay que mencionar a Jean-Jacques Rousseau, han pensado que el establecimiento de la democracia era imposible en los grandes pueblos. ¿Cómo puede deliberar un pueblo así? Entre los antiguos, todos los ciudadanos se reunían en una plaza; se comunicaban su voluntad [...] La invención del telégrafo es un nuevo dato que Rousseau no pudo incluir en sus cálculos. Puede servir para hablar a grandes distancias tan sencillamente y tan claramente como en una sala [...] No hay imposibilidad alguna de que todos los ciudadanos de Francia se comuniquen sus informaciones y sus voluntades, en un tiempo bastante corto, para que esta comunicación pueda ser considerada como instantánea.» Este texto data de marzo de 1795 y es obra de un hombre de ciencia: Alexandre Vandermonde (1735-1796), titular de la primera cátedra de economía política creada en Francia. En agosto de 1794, el ministerio de la Guerra había inaugurado la primera línea de telegrafía óptica (París-Lille).</q> Armand Mattelard ["Historia de la Sociedad de la Información"](http://es.scribd.com/doc/31032411/Mattelart-Armand-Historia-de-la-sociedad-de-la-informacion), pag. 32, "El nacimiento del discurso redentor sobre la comunicación a distancia".
[^4]: <q>Hoy nos parece natural, por establecida, la concepción descentralizada del poder, la articulación de las organizaciones humanas (Estados, empresas, asociaciones, etc.) en niveles jerárquicos correspondientes a espacios territoriales. Nos parece natural la estructura de representación social y política que de ahí deriva y nos parece natural que se produzca mediante progresivas fases de centralización (local, regional, nacional, internacional, global, etc.) de decisiones que en cada nivel se producen sobre un universo igual de temas. Esto no era así antes del telégrafo, ni siquiera en las organizaciones políticas más «avanzadas» surgidas de la Revolución francesa. La concepción centralizada era tan pura como el universo de temas era diferente en cada nivel (cuando había varios). La tendencia era una réplica del sistema de postas del Antiguo Régimen, el famoso centralismo jacobino. Las estructuras descentralizadas son producto de un problema técnico: por el deficiente aislamiento de los cables telegráficos de las primeras décadas, era imposible reproducir con los primeros telégrafos los largos recorridos de los correos, así que, dado que hacían falta más estaciones que postas y estas involucraban una cierta infraestructura específica, resultaba racional que actuaran como centralizadores locales distribuyendo los mensajes en una red que era ya descentralizada. A largo plazo estas estructuras tendrán su propia lógica, generando nuevos nodos superiores no nacionales, como las agencias de noticias primero o las primeras multinacionales después [...]</q>, David de Ugarte en ["El poder de las redes. Manual ilustrado para ciberactivistas"](http://lasindias.org/el-poder-de-las-redes/#breve-historia-de-las-redes-sociales)
